"""L0 — does a force-balanced resting configuration EXIST at all?

THE QUESTION, and why it is not a solver question.  Five inner solvers have failed to descend on the
resting residual, and 2026-08-15 excluded five candidate causes (non-conservativity, cross-link
pre-stress, iteration budget, solid-fluid coupling, shell feasibility).  What was never tested is
whether there is anything to descend TO.  ``driver.py``'s own docstring says there is not:

    "a relaxed cortex plus a positive turgor is not a valid resting baseline -- there is no
     force-balanced equilibrium there, which is why no inner solver converges from it"

The only stress that can oppose the turgor is active cortical hoop tension, and it is generated by the
resting bound-myosin setpoint -- two constants that are PI-GAP with NO DEFAULT, so every resting run
recorded so far had the tension source OFF by construction (`myosin_bound_after_step: 0`).  This run
turns it on.

THE AXIS, not a value.  PI ruling 2026-08-20: *"우리는 어떤 것에 대한 기준을 잡지 않고 생리 범위만을 일단
테스트용으로 잡는다. 그리고 모든 것을 믿지 않고 오직 테스트로 생각해서 돌린다."*  Standing ruling #1.
The per-head force axis is the bracket already recorded in ``params_i0b3.yaml`` -- and
``NMII_PER_HEAD_FORCE_SOURCE_AUDIT_2026-08-20.md`` establishes that NEITHER end is a measurement:
0.5 pN is an AFINES simulation parameter whose cited Kovacs 2003 is a transient-kinetics paper with no
force in it, and 2.0 pN is a constant from a kernel this project retired.  So the axis is declared as a
TEST AXIS and the `source` string says exactly that, rather than a citation that does not hold.

The FRACTION axis is the code's own admissible domain (0, 1], NOT a physiological band.  Scope, stated
so it cannot be misread later: this asks whether the mechanism can produce a balance point ANYWHERE in
its own domain.  It is not a claim about what fraction of NMII heads are bound in a cell.

⚠ WHAT THIS CANNOT ESTABLISH.  That a descending arm is the physiological resting state.  Descent means
a balance point exists and the solver can move toward it -- level 1 of the question.  Whether the state
reached is the resting cell is level 2, and needs D-1/D-2/D-3 (observables, bands, stability protocol),
none of which is decided.  See ``ENGINE_FORWARD_ACCEPTANCE_2026-08-20.md``.

THE CRITERION, RE-DECLARED 2026-08-20 AFTER RUN 1 WAS VOIDED.  Per point, from the StabilityReport:

    descent_ratio = residual_candidate / residual_start   (< 1 means the SOLVE went down)

⚠ WHY THIS IS A CORRECTION AND NOT A CONVENIENCE.  Run 1 (job 69) declared
``residual_end / residual_start``.  ``residual_end`` is read AFTER the outer accept/reject, the rollback
is bit-exact, and every point was rejected -- so end was restored to start in all ten arms and the ratio
was exactly 1.000000 everywhere.  The criterion could not have shown descent at any setpoint, which makes
its verdict VOID rather than negative; it is declared ``retract`` in ``results_manifest.yaml``.
``residual_candidate`` is what the inner solve actually REACHED before the outer step judged it, it was
present in every run-1 artifact, and it is the field the question was always about.

⚠ AND WHAT THIS CRITERION STILL CANNOT SAY.  ``residual_candidate`` descending means the SOLVE moved
downhill; the outer step may still reject it, and it did in all of run 1.  So a descent here licenses
"a direction of descent exists from this configuration" and NOT "the step is accepted".  Acceptance is a
separate predicate and this run does not test it.

A point DESCENDS iff ``descent_ratio < 1``.  No threshold is placed on how far: the prior is that
nothing descends at all, and the informative outcome is the sign, not the size.  Magnitudes are
recorded and are NOT quotable from this run.

THE NEGATIVE CONTROL, DECLARED BEFORE THE RUN, and it runs FIRST.  With the setpoint OFF the residual
must NOT descend.  **If the OFF arm descends too, this run has FAILED, not passed** -- the descent would
not be attributable to the tension source, and no ON point may be quoted.  This is written here, before
any data, because a control read after the fact is not one.

Sanity Gate (recorded per CLAUDE.md, before first execution):
  * dimensional -- fraction dimensionless in (0, 1]; per-head force [pN]; residual as the driver's own
    max|PF| [pN]; descent_ratio dimensionless.
  * boundary -- the OFF arm is the setpoint absent entirely (both constants None), which the build
    treats as unbound-at-rest, NOT fraction=0 (which the contract rejects as outside (0, 1]).
  * conservation/invariant -- nothing here integrates or accumulates; each point is an independent
    build + solve, and the ledger's own population counts are recorded per point.
  * CFL/precision -- untouched: dt and the inner solver are the driver's defaults so this run differs
    from the recorded resting runs in the setpoint ALONE.
  * sign sense -- descent_ratio < 1 is descent; the raw start/end are both recorded so the direction
    cannot be inferred from a ratio alone.
  * measurement protocol -- one build + one `run_from_resting` per point; each point's JSON is written
    the moment it finishes, so a timeout loses only the unfinished tail.

⚠ NO SILENT CAPS.  Points are run in the declared order below and each is timed.  If the wall budget
runs out, the run STOPS and records which points were never attempted, by name, in the summary.  A
partial sweep that does not say what it dropped reads as a complete one.

engine units: force pN, length um.  Runtime: NVIDIA Warp on CUDA only.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

#: The per-head axis: the two ends of the recorded I0-B3 bracket. Neither is a measurement — see the
#: source audit. A midpoint is included so a monotone trend can be distinguished from an endpoint effect.
PER_HEAD_FORCE_PN = (0.5, 1.0, 2.0)

#: The fraction axis: the contract's admissible domain, log-spaced. NOT a physiological band.
FRACTION = (0.01, 0.05, 0.20)

#: ⚠ THE AXIS RUN 1 WAS MISSING.  Run 1 varied the setpoint alone and found the residual INSENSITIVE to
#: it -- a 20x change in bound heads (88 -> 1,768) moved the ratio by nothing, all nine ON points
#: agreeing to the 7th decimal.  The reason is in the same artifacts: ``residual_start`` is 47.405172 at
#: BOTH 3,000 and 70,686 filaments, so the residual maximum is not on the cortex at all -- it is on the
#: membrane carrying the turgor.  ``RESTING_BASELINE_DIAGNOSIS_2026-07-23c.md`` §2 already says a
#: force-free ERM transmits nothing, and run 1 passed no preload, so the tethers were force-free at
#: build.  Cortical tension with no transmission path cannot move a membrane residual however much of it
#: there is.  The setpoint and the preload are therefore tested TOGETHER, as a 2x2 in their presence,
#: because either alone is predicted to do nothing and run 1 measured one half of that prediction.
PRELOAD = (False, True)

#: The source string that travels into every artifact. It says what the axis is instead of citing a
#: paper that does not support the number — see NMII_PER_HEAD_FORCE_SOURCE_AUDIT_2026-08-20.md.
TEST_AXIS_SOURCE = (
    "TEST AXIS 2026-08-20, NOT a sourced value. per-head 0.5-2.0 pN is the recorded I0-B3 bracket whose "
    "ends are an AFINES simulation parameter and a retired kernel constant; fraction spans the "
    "contract's admissible domain and is not a physiological band. Scope: tests whether the mechanism "
    "can produce a balance point anywhere in its own domain. PI ruling: band-as-test, not a citation."
)


def _point_order() -> list[dict]:
    """The declared run order: the 2x2 presence controls FIRST, then the axis.

    Run 1's lesson is why the 2x2 leads. It varied the setpoint alone and the residual did not respond,
    which the diagnosis had already predicted for a force-free ERM. So the first four points establish
    which of the four presence combinations moves anything at all, and only then is the axis swept — under
    both preload settings, so the axis is not read under a transmission path that was never open.

    A timeout therefore loses axis refinement, never the presence question.
    """
    f_mid, p_mid = FRACTION[1], PER_HEAD_FORCE_PN[1]
    pts: list[dict] = []
    for pre in PRELOAD:
        pts.append({"name": f"ctl_OFF_pre{int(pre)}", "fraction": None, "f_head_pn": None, "preload": pre})
        pts.append({"name": f"ctl_ON_pre{int(pre)}", "fraction": f_mid, "f_head_pn": p_mid, "preload": pre})
    for pre in PRELOAD:
        for f in FRACTION:
            for q in PER_HEAD_FORCE_PN:
                name = f"ax_f{f:g}_p{q:g}_pre{int(pre)}"
                if not any(x["name"] == name for x in pts):
                    pts.append({"name": name, "fraction": f, "f_head_pn": q, "preload": pre})
    return pts


def _run_point(pt: dict, args: argparse.Namespace, out_dir: Path) -> dict:
    """Run one point as its own driver process, so a crash costs one point rather than the sweep."""
    js = out_dir / f"{pt['name']}.json"
    cmd = [
        args.python, "-m", "aleph.components.incumbent.driver",
        "--n-filaments", str(args.n_filaments),
        "--n-inner", str(args.n_inner),
        "--dt-phys", str(args.dt_phys),
        "--device", args.device,
        "--json", str(js),
    ]
    # `driver.py:1531` declares this `action="store_true"`, NOT BooleanOptionalAction — so the flag is
    # PRESENT or ABSENT and `--no-preload-erm-balance` is an unrecognised argument. Passing it killed 11
    # of 22 points with rc=2 in run 2 before this was found.
    if pt["preload"]:
        cmd += ["--preload-erm-balance"]
    if pt["fraction"] is not None:
        cmd += [
            "--resting-bound-myosin-fraction", str(pt["fraction"]),
            "--resting-bound-myosin-force", str(pt["f_head_pn"]),
            "--resting-bound-myosin-source", TEST_AXIS_SOURCE,
        ]
    t0 = time.time()
    done = subprocess.run(cmd, capture_output=True, text=True)
    wall = time.time() - t0
    rec: dict = {"point": pt, "wall_s": wall, "returncode": done.returncode, "json": str(js)}
    if done.returncode != 0:
        rec["stderr_tail"] = done.stderr[-2000:]
        return rec
    try:
        payload = json.loads(js.read_text())
    except Exception as exc:  # noqa: BLE001 — a point that wrote no readable artifact is a failed point
        rec["error"] = f"unreadable artifact: {exc}"
        return rec
    rep = payload.get("report", {})
    # `myosin_bound_after_step` lives in the population LEDGER, not the stability report — found the hard
    # way when the instrument positive control aborted job 68 five minutes in, looking in the report.
    led = payload.get("ledger") or rep.get("ledger") or {}
    r0 = rep.get("residual_start")
    r1 = rep.get("residual_candidate")   # what the SOLVE reached, before the outer accept/reject
    rec.update({
        "residual_start": r0, "residual_candidate": r1, "residual_end": rep.get("residual_end"),
        "descent_ratio": (r1 / r0) if (r0 not in (None, 0) and r1 is not None) else None,
        "descends": (r1 < r0) if (r0 is not None and r1 is not None) else None,
        "inner_converged": rep.get("inner_converged"),
        "myosin_bound_after_step": led.get("myosin_bound_after_step"),
        "erm_bound_after_step": led.get("erm_bound_after_step"),
        "preload_mechanically_feasible_upper_bound": led.get("preload_mechanically_feasible_upper_bound"),
        "outer_accepted": rep.get("outer_accepted"), "outer_rolled_back": rep.get("outer_rolled_back"),
        "r_mean_start": rep.get("r_mean_start"), "r_mean_end": rep.get("r_mean_end"),
    })
    return rec


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--n-filaments", type=int, default=70686, help="full native cortex count")
    ap.add_argument("--n-inner", type=int, default=4000,
                    help="MATCHES the committed negative result at 4c165576 (4,000 inner iterations, full "
                         "native), so this A/B differs from it in the SETPOINT ALONE. Budget matters to the "
                         "sign here: that record measured -0.52%% at 60 iterations and +0.14%% at 4,000, so a "
                         "descent read at a smaller budget would not be comparable to the arm it is "
                         "supposed to overturn.")
    ap.add_argument("--dt-phys", type=float, default=0.05)
    ap.add_argument("--device", type=str, default="cuda")
    ap.add_argument("--python", type=str, default=sys.executable)
    ap.add_argument("--budget-s", type=float, default=39600.0, help="wall budget; stop before overrunning")
    ap.add_argument("--out", type=Path, required=True)
    args = ap.parse_args()

    out_dir = args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    points = _point_order()
    started = time.time()
    results: list[dict] = []
    skipped: list[str] = []

    for i, pt in enumerate(points):
        elapsed = time.time() - started
        # Stop BEFORE starting a point we cannot finish: use the slowest point seen so far as the estimate.
        worst = max((r["wall_s"] for r in results), default=0.0)
        if results and elapsed + worst > args.budget_s:
            skipped = [p["name"] for p in points[i:]]
            print(f"[l0] STOPPING: {elapsed:.0f}s elapsed, slowest point {worst:.0f}s, budget "
                  f"{args.budget_s:.0f}s. NOT ATTEMPTED: {skipped}", flush=True)
            break
        print(f"[l0] ({i+1}/{len(points)}) {pt['name']} ...", flush=True)
        rec = _run_point(pt, args, out_dir)
        results.append(rec)
        print(f"[l0]   rc={rec['returncode']} wall={rec['wall_s']:.0f}s "
              f"descends={rec.get('descends')} ratio={rec.get('descent_ratio')} "
              f"bound={rec.get('myosin_bound_after_step')}", flush=True)
        (out_dir / "sweep_partial.json").write_text(json.dumps(results, indent=2, default=float))

    controls = [r for r in results if r["point"]["fraction"] is None]
    control = controls[0] if controls else None
    on = [r for r in results if r["point"]["fraction"] is not None]
    failed = [r["point"]["name"] for r in results if r["returncode"] != 0 or r.get("descent_ratio") is None]
    verdict = "INCONCLUSIVE"
    note = ""
    # A verdict rendered over points that never ran is the silent-cap failure this file's header forbids.
    # Run 2 produced `NO_DESCENT_ANYWHERE` while 11 of its 22 points had died with rc=2, because this
    # check did not exist. It refuses FIRST, before any of the physics branches below.
    if failed:
        verdict = "VOID_INCOMPLETE"
        note = (f"{len(failed)} of {len(results)} attempted points produced no usable result "
                f"({failed}). No verdict is rendered over a partial set: the arms that did run may be "
                "quoted individually from their own artifacts, and this summary claims nothing.")
    elif control is None:
        note = "the negative control never ran; no ON point is attributable and none may be quoted"
    elif any(r.get("descends") for r in controls):
        verdict = "FAILED_CONTROL"
        note = ("the setpoint-OFF arm DESCENDED. Declared before the run: if the control descends the "
                "run has failed, because descent is then not attributable to the tension source. No ON "
                "point may be quoted from this run.")
    elif any(r.get("descends") for r in on):
        verdict = "DESCENT_WITH_CLEAN_CONTROL"
        note = ("at least one ON point descended while the OFF control did not. This licenses only the "
                "existence claim at level 1 — a balance point exists and the solver moves toward it. It "
                "does NOT establish that the state reached is the physiological resting cell.")
    elif on:
        verdict = "NO_DESCENT_ANYWHERE"
        note = ("no ON point descended and neither did the control. The tension source does not create a "
                "reachable balance point anywhere on this axis, which is a NEGATIVE result about the "
                "mechanism and not about the solver.")
    summary = {
        "schema": "ffn-ac-l0-balance-exists-v1",
        "declared_before_run": {
            "criterion": "descent_ratio = residual_candidate / residual_start < 1",
            "supersedes": "run 1 (job 69) declared residual_end, which the bit-exact rollback pins to "
                          "residual_start on a rejected step; its verdict is VOID, declared retract",
            "negative_control": "setpoint OFF must NOT descend; if it does the run FAILED",
            "axis_per_head_force_pn": list(PER_HEAD_FORCE_PN),
            "axis_fraction": list(FRACTION),
            "axis_preload_erm_balance": list(PRELOAD),
            "source_string": TEST_AXIS_SOURCE,
        },
        "verdict": verdict, "note": note,
        "n_attempted": len(results), "n_declared": len(points),
        "not_attempted": skipped,
        "results": results,
    }
    (out_dir / "l0_summary.json").write_text(json.dumps(summary, indent=2, default=float))
    print(f"\n[l0] VERDICT: {verdict}\n[l0] {note}", flush=True)
    if skipped:
        print(f"[l0] NOT ATTEMPTED ({len(skipped)}): {skipped}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
