"""Circular bead-spring cortex generation (KU-3.1, KU-3.17).

The outer cortex of a Phase 1 single cell is represented as a discrete
2D fiber network whose fiber centers sit on a circle of radius
``R_cell`` and whose orientations are perturbations around the local
tangent (counter-clockwise). Each fiber is discretised into
``beads_per_fiber`` beads with the same WLC bead-spring form as the
ECM (KU-1.24); cross-links between neighbouring fibers are harmonic
springs (KU-1.28) generated by 2D segment intersection (KU-1.27) and
then filtered to retain only nearby pairs (``xl_cutoff``).

Free-space convention
---------------------
A single isolated cell has no periodic box. We supply an artificial
``box_size = 100 · R_cell`` to all reused ECM kernels so the
minimum-image arithmetic is a no-op for any realistic cortex bond or
cross-link displacement (≪ box_size / 2). The cortex is **not**
wrapped — bead positions are real Cartesian coordinates.

Initial-condition variants
--------------------------
``generate_cortex`` produces a perfectly circular cortex (radius
``R_cell``) sufficient for cortical-tension equilibrium tests.
``generate_elliptical_cortex`` re-maps the same fiber population onto
an ellipse with semi-axes (a, b) for the KU-3.1 VALIDATION rounding
test; the per-fiber tangent direction is recomputed from the
elliptical local tangent so the construction is geometrically
consistent.

Sanity Gate
-----------
1. Dimensional analysis: R_cell [m], L_fiber [m], rest_length [m].
   No time integration in this module → no CFL check.
2. Boundary cases:
   - beads_per_fiber < 2 → ValueError (no bonds).
   - n_cortex_fibers < 3 → ValueError (cannot cover a closed loop).
   - kappa_vm_tangent ≤ 0 → uniform-angle fallback (no alignment bias).
3. Conservation: stateless generator; no quantities to conserve.
4. Numerical sanity: float64; vMF draws use rng.vonmises; no NaN paths
   because all denominators are positive constants (R, ℓ₀, L_fiber).
5. Sign / sense: tangent direction t̂(θ) = (-sin θ, cos θ) points
   counter-clockwise; centres on a circle drift outward only under
   cortical tension if R_eff > R_cell, inward otherwise (force kernel
   in :mod:`acs_kb.cell.force_balance` handles the sign).
6. Measurement protocol: ⟨z⟩ and coverage ratio are reported per
   bead and per circumference respectively, matching the comparisons
   that the Sanity Gate (`gate_phase1_cell_cortex`) makes against
   KU-3.17 ranges.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np

from acs_kb.ecm.cross_links import CrossLink, _segment_intersections


@dataclass(slots=True)
class Cortex:
    """Discrete 2D cortex state.

    Attributes
    ----------
    bead_positions : np.ndarray, shape (n_fibers, n_beads, 2)
        Real (un-wrapped) Cartesian bead coordinates in meters.
    fiber_centers : np.ndarray, shape (n_fibers, 2)
        Centre of each fiber in meters (lies on the construction
        ellipse / circle).
    fiber_endpoints : np.ndarray, shape (n_fibers, 2, 2)
        (p1, p2) endpoint pair for each rod, used by the segment-
        intersection kernel.
    fiber_orientations : np.ndarray, shape (n_fibers,)
        Per-fiber director angle θ in radians.
    fiber_ids : np.ndarray, shape (n_fibers,)
    rest_length : float
        Bond rest length ℓ₀ = L_fiber / (n_beads - 1) (m).
    fiber_length : float
        Contour length per cortex fiber (m).
    cell_center : np.ndarray, shape (2,)
        Cell centre (m).
    R_cell : float
        Construction radius (m).
    box_size : float
        Artificial free-space box for ECM-kernel minimum-image arithmetic.
    cross_links : list[CrossLink]
        Harmonic XL bonds between cortex fibers (KU-1.28 form).
    params : dict
        Snapshot of input parameters (KU-3.17 defaults).
    """

    bead_positions: np.ndarray
    fiber_centers: np.ndarray
    fiber_endpoints: np.ndarray
    fiber_orientations: np.ndarray
    fiber_ids: np.ndarray
    rest_length: float
    fiber_length: float
    cell_center: np.ndarray
    R_cell: float
    box_size: float
    cross_links: list[CrossLink] = field(default_factory=list)
    params: dict[str, Any] = field(default_factory=dict)

    @property
    def n_fibers(self) -> int:
        return int(self.bead_positions.shape[0])

    @property
    def n_beads_per_fiber(self) -> int:
        return int(self.bead_positions.shape[1])

    @property
    def n_beads_total(self) -> int:
        return int(self.bead_positions.shape[0] * self.bead_positions.shape[1])


def _sample_tangent_angles(
    angular_positions: np.ndarray,
    kappa_vm: float,
    rng: np.random.Generator,
) -> np.ndarray:
    """Sample fiber director angles around the local CCW tangent.

    Local tangent angle at angular position θ on a circle is θ + π/2.
    For κ > 0 we draw deviations from ``rng.vonmises(0, κ)``; for
    κ ≤ 0 we fall back to a uniform draw on [0, π) (head-tail
    symmetric — no alignment bias).
    """
    tangent_mu = angular_positions + 0.5 * np.pi
    if kappa_vm <= 0.0:
        deviations = rng.uniform(-0.5 * np.pi, 0.5 * np.pi, size=angular_positions.size)
    else:
        deviations = rng.vonmises(mu=0.0, kappa=kappa_vm, size=angular_positions.size)
    return np.mod(tangent_mu + deviations, np.pi)


def _bead_offsets(L_fiber: float, beads_per_fiber: int) -> np.ndarray:
    """Per-bead arc-length offset s ∈ [-L/2, +L/2] along the director."""
    return np.linspace(-0.5 * L_fiber, 0.5 * L_fiber, beads_per_fiber)


def _filter_cross_links_by_cutoff(
    candidates: list[CrossLink],
    bead_positions: np.ndarray,
    cutoff: float,
) -> list[CrossLink]:
    """Keep only XLs whose nearest-bead distance is below ``cutoff``."""
    if not candidates:
        return []
    kept: list[CrossLink] = []
    for xl in candidates:
        ra = bead_positions[xl.fiber_a, xl.bead_a]
        rb = bead_positions[xl.fiber_b, xl.bead_b]
        if np.linalg.norm(rb - ra) <= cutoff:
            kept.append(xl)
    return kept


def _build_cross_links(
    bead_positions: np.ndarray,
    fiber_endpoints: np.ndarray,
    L_fiber: float,
    beads_per_fiber: int,
    box_size: float,
    xl_cutoff: float,
    xl_stiffness: float,
) -> list[CrossLink]:
    """Generate cortex cross-links by 2D segment intersection + cutoff filter.

    The same KU-1.27 segment-intersection kernel as the ECM is reused;
    here we additionally accept the link **only if** the two nearest
    beads are within ``xl_cutoff`` of each other (KU-3.17 Phase 1
    simplification of KU-1.28; the cortex's structural cross-link
    (α-actinin, filamin) acts only over a ~100 nm reach, so a cutoff
    of 0.5 μm conservatively keeps geometrically credible links).
    """
    iu, ju, s_a, s_b = _segment_intersections(fiber_endpoints)
    if iu.size == 0:
        return []

    bead_a = np.clip(
        np.round((s_a + 0.5 * L_fiber) * (beads_per_fiber - 1) / L_fiber),
        0, beads_per_fiber - 1,
    ).astype(np.int64)
    bead_b = np.clip(
        np.round((s_b + 0.5 * L_fiber) * (beads_per_fiber - 1) / L_fiber),
        0, beads_per_fiber - 1,
    ).astype(np.int64)

    ra = bead_positions[iu, bead_a, :]
    rb = bead_positions[ju, bead_b, :]
    # Free-space cortex: MI subtraction is a no-op (box_size ≫ any displacement)
    # but kept for symmetry with the ECM kernels that consume these links.
    delta = rb - ra
    delta -= box_size * np.round(delta / box_size)
    rest = np.linalg.norm(delta, axis=1)

    candidates = [
        CrossLink(
            fiber_a=int(iu[k]), bead_a=int(bead_a[k]),
            fiber_b=int(ju[k]), bead_b=int(bead_b[k]),
            rest_length=float(rest[k]),
            stiffness=float(xl_stiffness),
        )
        for k in range(iu.size)
    ]
    return _filter_cross_links_by_cutoff(candidates, bead_positions, xl_cutoff)


def generate_cortex(
    R_cell: float,
    n_cortex_fibers: int,
    L_cortex_fiber: float,
    beads_per_fiber: int,
    *,
    kappa_vm_tangent: float = 5.0,
    xl_cutoff: float = 0.5e-6,
    xl_stiffness: float = 1.0e-3,
    cell_center: np.ndarray | None = None,
    box_size: float | None = None,
    seed: int | None = None,
    params: dict[str, Any] | None = None,
) -> Cortex:
    """Generate a circular discrete-fiber cortex (KU-3.1, KU-3.17).

    Parameters
    ----------
    R_cell : float
        Cell radius (m). Fiber centers lie on this circle.
    n_cortex_fibers : int
        Number of cortex fibers (≥ 3).
    L_cortex_fiber : float
        Contour length per cortex fiber (m).
    beads_per_fiber : int
        Number of beads per fiber (≥ 2). KU-3.17 default is 5.
    kappa_vm_tangent : float, default 5.0
        Concentration parameter of the von Mises deviation around the
        local tangent. Larger κ = tighter alignment with the cortex
        tangent. KU-3.17 Phase-1 default.
    xl_cutoff : float, default 0.5 μm
        Maximum bead-bead distance for a candidate XL to be retained.
    xl_stiffness : float, default 1 pN/nm = 1e-3 N/m
        Cross-link harmonic stiffness (KU-1.28).
    cell_center : np.ndarray or None
        2D centre (m); defaults to origin.
    box_size : float or None
        Free-space MI box (m); defaults to 100 · R_cell.
    seed : int or None
    params : dict or None

    Returns
    -------
    Cortex
    """
    if beads_per_fiber < 2:
        raise ValueError("beads_per_fiber must be ≥ 2.")
    if n_cortex_fibers < 3:
        raise ValueError("n_cortex_fibers must be ≥ 3 to cover a closed loop.")
    if L_cortex_fiber <= 0 or R_cell <= 0:
        raise ValueError("Lengths must be positive.")

    rng = np.random.default_rng(seed)
    if cell_center is None:
        cell_center = np.zeros(2, dtype=np.float64)
    else:
        cell_center = np.asarray(cell_center, dtype=np.float64)
    if box_size is None:
        box_size = 100.0 * R_cell

    angular_positions = rng.uniform(0.0, 2.0 * np.pi, size=n_cortex_fibers)
    centers = cell_center + R_cell * np.stack(
        [np.cos(angular_positions), np.sin(angular_positions)], axis=1
    )
    angles = _sample_tangent_angles(angular_positions, kappa_vm_tangent, rng)

    s = _bead_offsets(L_cortex_fiber, beads_per_fiber)
    directors = np.stack([np.cos(angles), np.sin(angles)], axis=1)
    offsets = s[None, :, None] * directors[:, None, :]
    bead_positions = centers[:, None, :] + offsets

    endpoint_offsets = np.array([-0.5 * L_cortex_fiber, +0.5 * L_cortex_fiber])
    fiber_endpoints = (
        centers[:, None, :] + endpoint_offsets[None, :, None] * directors[:, None, :]
    )

    rest_length = L_cortex_fiber / (beads_per_fiber - 1)

    xls = _build_cross_links(
        bead_positions=bead_positions,
        fiber_endpoints=fiber_endpoints,
        L_fiber=L_cortex_fiber,
        beads_per_fiber=beads_per_fiber,
        box_size=box_size,
        xl_cutoff=xl_cutoff,
        xl_stiffness=xl_stiffness,
    )

    return Cortex(
        bead_positions=bead_positions.astype(np.float64, copy=False),
        fiber_centers=centers.astype(np.float64, copy=False),
        fiber_endpoints=fiber_endpoints.astype(np.float64, copy=False),
        fiber_orientations=angles.astype(np.float64, copy=False),
        fiber_ids=np.arange(n_cortex_fibers, dtype=np.int64),
        rest_length=float(rest_length),
        fiber_length=float(L_cortex_fiber),
        cell_center=cell_center,
        R_cell=float(R_cell),
        box_size=float(box_size),
        cross_links=xls,
        params=dict(params or {}),
    )


def generate_elliptical_cortex(
    semi_major: float,
    semi_minor: float,
    n_cortex_fibers: int,
    L_cortex_fiber: float,
    beads_per_fiber: int,
    *,
    kappa_vm_tangent: float = 5.0,
    xl_cutoff: float = 0.5e-6,
    xl_stiffness: float = 1.0e-3,
    cell_center: np.ndarray | None = None,
    box_size: float | None = None,
    seed: int | None = None,
    params: dict[str, Any] | None = None,
) -> Cortex:
    """Generate an elliptical cortex (KU-3.1 VALIDATION initial condition).

    Same construction as :func:`generate_cortex` but fiber centres lie
    on an ellipse with axes (``semi_major``, ``semi_minor``) and each
    fiber tangent is taken from the local elliptical tangent
    direction. The effective radius used for downstream free-space
    box-size defaults to ``max(a, b)``.
    """
    if beads_per_fiber < 2:
        raise ValueError("beads_per_fiber must be ≥ 2.")
    if n_cortex_fibers < 3:
        raise ValueError("n_cortex_fibers must be ≥ 3 to cover a closed loop.")
    if semi_major <= 0 or semi_minor <= 0 or L_cortex_fiber <= 0:
        raise ValueError("Lengths must be positive.")

    rng = np.random.default_rng(seed)
    if cell_center is None:
        cell_center = np.zeros(2, dtype=np.float64)
    else:
        cell_center = np.asarray(cell_center, dtype=np.float64)
    R_eff = max(semi_major, semi_minor)
    if box_size is None:
        box_size = 100.0 * R_eff

    a = float(semi_major)
    b = float(semi_minor)
    t = rng.uniform(0.0, 2.0 * np.pi, size=n_cortex_fibers)
    centers = cell_center + np.stack([a * np.cos(t), b * np.sin(t)], axis=1)

    # Local CCW tangent on the ellipse: dR/dt = (-a sin t, b cos t).
    tangents = np.stack([-a * np.sin(t), b * np.cos(t)], axis=1)
    tangent_norm = np.linalg.norm(tangents, axis=1)
    tangent_norm = np.where(tangent_norm > 0.0, tangent_norm, 1.0)
    tangents = tangents / tangent_norm[:, None]
    tangent_mu = np.arctan2(tangents[:, 1], tangents[:, 0])

    if kappa_vm_tangent <= 0.0:
        deviations = rng.uniform(-0.5 * np.pi, 0.5 * np.pi, size=n_cortex_fibers)
    else:
        deviations = rng.vonmises(mu=0.0, kappa=kappa_vm_tangent, size=n_cortex_fibers)
    angles = np.mod(tangent_mu + deviations, np.pi)

    s = _bead_offsets(L_cortex_fiber, beads_per_fiber)
    directors = np.stack([np.cos(angles), np.sin(angles)], axis=1)
    offsets = s[None, :, None] * directors[:, None, :]
    bead_positions = centers[:, None, :] + offsets

    endpoint_offsets = np.array([-0.5 * L_cortex_fiber, +0.5 * L_cortex_fiber])
    fiber_endpoints = (
        centers[:, None, :] + endpoint_offsets[None, :, None] * directors[:, None, :]
    )

    rest_length = L_cortex_fiber / (beads_per_fiber - 1)
    xls = _build_cross_links(
        bead_positions=bead_positions,
        fiber_endpoints=fiber_endpoints,
        L_fiber=L_cortex_fiber,
        beads_per_fiber=beads_per_fiber,
        box_size=box_size,
        xl_cutoff=xl_cutoff,
        xl_stiffness=xl_stiffness,
    )

    return Cortex(
        bead_positions=bead_positions.astype(np.float64, copy=False),
        fiber_centers=centers.astype(np.float64, copy=False),
        fiber_endpoints=fiber_endpoints.astype(np.float64, copy=False),
        fiber_orientations=angles.astype(np.float64, copy=False),
        fiber_ids=np.arange(n_cortex_fibers, dtype=np.int64),
        rest_length=float(rest_length),
        fiber_length=float(L_cortex_fiber),
        cell_center=cell_center,
        R_cell=float(R_eff),
        box_size=float(box_size),
        cross_links=xls,
        params=dict(params or {}),
    )


def measure_coverage_ratio(cortex: Cortex) -> float:
    """Mean fiber coverage = N_f · L_f / (2π R_cell)."""
    circumference = 2.0 * np.pi * cortex.R_cell
    return float(cortex.n_fibers * cortex.fiber_length / circumference)


def measure_aspect_ratio(cortex: Cortex) -> float:
    """Aspect ratio of the cortex bead cloud (PCA, eigenvalue ratio).

    Computes the 2×2 covariance of all bead positions (mean-centred)
    and returns √(λ_max / λ_min), matching the conventional ellipse
    aspect-ratio definition. KU-3.1 VALIDATION uses this as the
    rounding-test scalar.
    """
    pts = cortex.bead_positions.reshape(-1, 2)
    pts = pts - pts.mean(axis=0, keepdims=True)
    cov = np.cov(pts.T)
    eigs = np.linalg.eigvalsh(cov)
    if eigs.min() <= 0.0:
        return float("inf")
    return float(np.sqrt(eigs.max() / eigs.min()))


def measure_mean_radius(cortex: Cortex) -> float:
    """Mean bead distance from the (current) centroid."""
    pts = cortex.bead_positions.reshape(-1, 2)
    centroid = pts.mean(axis=0)
    return float(np.linalg.norm(pts - centroid, axis=1).mean())


def measure_coordination(cortex: Cortex) -> float:
    """Per-bead coordination ⟨z⟩ = backbone_z + 2 N_xl / N_beads."""
    beads = cortex.n_beads_per_fiber
    if beads < 2:
        return 0.0
    backbone_z = (2.0 * (beads - 2) + 2.0) / beads
    n_beads_total = cortex.n_beads_total
    if n_beads_total <= 0:
        return 0.0
    return backbone_z + 2.0 * len(cortex.cross_links) / n_beads_total
