#!/usr/bin/env python3
"""build_index.py — write the vault's entry point, `00_INDEX.md` (refresh step 5).

WHY THIS EXISTS.  `refresh.sh`'s sanity block has printed ``index present: no`` on every run since
that check was written, because nothing in the pipeline ever produced the file it asks about.  A
sanity line that can only ever fail is not a check, it is noise — and what it was quietly reporting
is real: a 1,600-note vault with no entry point, so opening the vault lands on whatever note sorts
first (a paper) rather than on the graph.

Runs LAST, after the four steps that populate the vault, so the counts describe what those steps
actually produced rather than what they were expected to.

Regenerated wholesale every refresh, like every other note here: Notion is the source of truth and a
hand-edit to this file is erased by the next run, which the header of the generated file says.
"""
from collections import Counter
from datetime import date
from pathlib import Path

from pathlib import Path

vault = Path("vault")
notes = sorted(p for p in vault.glob("*.md") if p.stem != "00_INDEX")

#: (display name, predicate) — reading order of the graph, leaves last.
GROUPS = [
    ("Day-logs — the project narrative", lambda s: s.startswith("DL_")),
    ("KnowledgeClaim — literature claims", lambda s: s.startswith(("KB-", "KU-"))),
    ("ModelContract — adopted approximations", lambda s: s.startswith("MC-")),
    ("ValidationGate — pass/fail gates", lambda s: s.startswith("VG-")),
    ("Parameter — concrete values", lambda s: s.startswith("PARAM-")),
    ("RunResult — run pointers", lambda s: s.startswith("RUN-")),
    ("DecisionLedger — decisions", lambda s: s.startswith("DEC-")),
    ("Code / test / doc nodes", lambda s: s[:2] in ("C_", "T_", "D_")),
]
LEAF = "SourceEvidence — papers (leaves)"

counts = Counter()
for n in notes:
    for name, pred in GROUPS:
        if pred(n.stem):
            counts[name] += 1
            break
    else:
        counts[LEAF] += 1

hubs = [h for h in ("DL_Dev_Logs_Hub", "DL_Status_Board") if (vault / f"{h}.md").exists()]

L = [
    "---", "type: Index", f"generated: {date.today().isoformat()}", "---", "",
    "# ffn_cellsim Contract-Graph — vault index", "",
    "> **Generated by `refresh.sh`. Do not hand-edit this vault or `kb.duckdb`** — Notion is the",
    "> single source of truth; fix it there and refresh. A hand-edit here is erased by the next run.",
    "", "## Start here", "",
]
L += [f"- [[{h}]]" for h in hubs] or ["- (no hub note — run `devlogs_to_obsidian.py`)"]
L += ["", "## What is in the vault", "", "| Node type | Notes |", "|---|---:|"]
for name, _ in GROUPS:
    if counts.get(name):
        L.append(f"| {name} | {counts[name]} |")
if counts.get(LEAF):
    L.append(f"| {LEAF} | {counts[LEAF]} |")
L += [f"| **total** | **{len(notes)}** |", "",
      "## How to read it", "",
      '- structure, "what links to X" -> this vault.',
      "- relational / aggregate / multi-hop -> `../../tag_kb/tag_query.py`.",
      "- a passage from a paper -> the BM25 content layer in `kb.duckdb`.", ""]

(vault / "00_INDEX.md").write_text("\n".join(L) + "\n", encoding="utf-8")
print(f"  wrote 00_INDEX.md ({len(notes)} notes indexed)")
