#!/usr/bin/env python3
"""#3 — add the Notion **Dev Logs & Reviews** board to the Obsidian vault.

Run AFTER notion_to_obsidian.py (it appends to the vault; never wipes).

The Contract-Graph exporter (#1) covers the 8 normalized DBs. The Dev Logs board
is NOT one of those DBs — it is a page-with-blocks: a status-board table tree plus
~48 milestone day-log child pages (prose). This script mirrors that narrative:

 - DL_Dev_Logs_Hub      — the parent page's prose (boot point / rules / index) +
                          links to every day-log + the status board.
 - DL_Status_Board      — the status-board / open-items tables rendered to markdown.
 - DL_<day-log title>   — one node per child page, FULL rendered prose body.

Cross-linking (the point): every day-log's prose is scanned for Contract-Graph
identifiers (KB-/KU-/MC-/VG-/RUN-/DEC-/H5-LP-/PARAM-) and for distinctive node
names already in the vault (paper keys, parameter names). Each hit becomes a
`relates::` wikilink, so the project NARRATIVE ("what we did") connects to the
KNOWLEDGE GRAPH ("what we know") in one component. Each day-log also `partof::`
the hub, so the DevLog cluster stays connected even when a log cites no id.

Notion = source of truth; the vault is regenerated by refresh.sh on demand.
"""
from __future__ import annotations
import json, re, time
import requests

# reuse the #1 exporter's conventions (token, headers, slugify, paths)
from notion_to_obsidian import (
    get_token, headers, slugify, VAULT, API, NOTION_VERSION,
)

# The Dev Logs & Reviews board (a page, not a DB).
DEVLOGS_PAGE = "365120daec5d81969e74ffbb757d55c8"

DEVLOG_COLOR = 0xff9800  # orange — narrative / project log
MAX_LINKS_PER_LOG = 50   # cap cross-links so a single log can't become a mega-hub


# ----------------------------------------------------------------------------- API
def _req(method, url, tok, **kw):
    """One request with 429/5xx retry (Notion rate limit ~3 req/s)."""
    for attempt in range(6):
        r = requests.request(method, url, headers=headers(tok), timeout=30, **kw)
        if r.status_code == 429:
            time.sleep(float(r.headers.get("Retry-After", 1.0)) + 0.2)
            continue
        if r.status_code >= 500:
            time.sleep(0.5 * (attempt + 1))
            continue
        r.raise_for_status()
        return r.json()
    r.raise_for_status()
    return r.json()


def get_children(block_id, tok):
    """All child blocks of a page/block (paginated)."""
    out, cursor = [], None
    base = f"{API}/blocks/{block_id}/children?page_size=100"
    while True:
        url = base + (f"&start_cursor={cursor}" if cursor else "")
        data = _req("GET", url, tok)
        out.extend(data["results"])
        if not data.get("has_more"):
            break
        cursor = data["next_cursor"]
        time.sleep(0.12)
    return out


# -------------------------------------------------------------------- rich text -> md
def rich(rt):
    """Notion rich_text array -> inline markdown (bold/italic/code/links preserved)."""
    parts = []
    for x in rt or []:
        t = x.get("plain_text", "")
        if not t:
            continue
        a = x.get("annotations", {})
        if a.get("code"):
            t = f"`{t}`"
        if a.get("bold"):
            t = f"**{t}**"
        if a.get("italic"):
            t = f"*{t}*"
        if a.get("strikethrough"):
            t = f"~~{t}~~"
        href = x.get("href")
        if href:
            t = f"[{t}]({href})"
        parts.append(t)
    return "".join(parts)


# ------------------------------------------------------------------- blocks -> md
def render(blocks, tok, discovered, depth=0):
    """Recursively render a list of Notion blocks to markdown lines.

    `discovered` accumulates {page_id: title} for any nested child_page so the
    caller can also export those as their own day-log nodes.
    """
    lines = []
    pad = "  " * depth
    num = 0
    for b in blocks:
        bt = b["type"]
        data = b.get(bt, {})
        kids = b.get("has_children")

        if bt == "paragraph":
            txt = rich(data.get("rich_text"))
            lines.append(pad + txt if txt else "")
        elif bt in ("heading_1", "heading_2", "heading_3"):
            hashes = {"heading_1": "#", "heading_2": "##", "heading_3": "###"}[bt]
            lines += ["", f"{hashes} {rich(data.get('rich_text'))}", ""]
        elif bt == "bulleted_list_item":
            lines.append(f"{pad}- {rich(data.get('rich_text'))}")
        elif bt == "numbered_list_item":
            num += 1
            lines.append(f"{pad}{num}. {rich(data.get('rich_text'))}")
        elif bt == "to_do":
            mark = "x" if data.get("checked") else " "
            lines.append(f"{pad}- [{mark}] {rich(data.get('rich_text'))}")
        elif bt == "toggle":
            lines += [f"{pad}- {rich(data.get('rich_text'))}"]
        elif bt == "quote":
            lines.append(f"{pad}> {rich(data.get('rich_text'))}")
        elif bt == "callout":
            emoji = (data.get("icon") or {}).get("emoji", "💡")
            lines.append(f"{pad}> {emoji} {rich(data.get('rich_text'))}")
        elif bt == "code":
            lang = data.get("language", "")
            lines += [f"{pad}```{lang}", rich(data.get("rich_text")), f"{pad}```"]
            kids = False
        elif bt == "equation":
            lines += ["", f"$$ {data.get('expression','')} $$", ""]
        elif bt == "divider":
            lines += ["", "---", ""]
        elif bt == "table":
            lines += render_table(b["id"], tok, pad)
            kids = False
        elif bt == "child_page":
            title = data.get("title", "untitled")
            pid = b["id"].replace("-", "")
            discovered[pid] = title
            lines.append(f"{pad}- ↳ [[{daylog_stem(title)}]]")
            kids = False  # exported separately as its own node
        elif bt == "child_database":
            lines.append(f"{pad}- 🗂️ (embedded database: {data.get('title','')})")
            kids = False
        elif bt in ("bookmark", "embed", "link_preview"):
            url = data.get("url", "")
            lines.append(f"{pad}- 🔗 {url}")
        elif bt in ("image", "video", "file", "pdf"):
            f = data.get("file") or data.get("external") or {}
            lines.append(f"{pad}- 📎 [{bt}]({f.get('url','')})")
        elif bt == "link_to_page":
            lines.append(f"{pad}- ↪ (linked Notion page)")
        elif bt in ("column_list", "column", "synced_block"):
            pass  # pure containers: fall through to recurse children
        elif bt in ("table_of_contents", "breadcrumb", "unsupported"):
            continue
        else:
            txt = rich(data.get("rich_text")) if isinstance(data, dict) else ""
            if txt:
                lines.append(pad + txt)

        if kids:
            child_blocks = get_children(b["id"], tok)
            lines += render(child_blocks, tok, discovered, depth + 1)
    return lines


def render_table(table_id, tok, pad=""):
    rows = get_children(table_id, tok)
    md, header_done = [""], False
    for r in rows:
        if r["type"] != "table_row":
            continue
        cells = [rich(c).replace("|", "\\|") or " " for c in r["table_row"]["cells"]]
        md.append(pad + "| " + " | ".join(cells) + " |")
        if not header_done:
            md.append(pad + "| " + " | ".join("---" for _ in cells) + " |")
            header_done = True
    md.append("")
    return md


# ---------------------------------------------------------------------- naming
def daylog_stem(title):
    return "DL_" + slugify(title)


def extract_meta(title):
    """Pull a date (YYYY-MM-DD) and unit (H.x) out of a day-log title, if present."""
    fm = {}
    d = re.search(r"\d{4}-\d{2}-\d{2}", title)
    if d:
        fm["date"] = d.group(0)
    u = re.search(r"\bH\.?(\d+[A-Za-zα-ω]?)", title)
    if u:
        fm["unit"] = "H." + u.group(1)
    return fm


# ------------------------------------------------------------------- cross-links
ID_RE = re.compile(
    r"\b(KB-[0-9A-Za-z.]+|KU-[0-9A-Za-z.]+|MC-[\w.-]+|VG-[\w.-]+"
    r"|RUN-[\w.-]+|DEC-[\w.-]+|H5-LP-[\w.-]+|PARAM-[\w.-]+)\b"
)
_PREFIXES = ("C_", "T_", "D_", "DL_")


def build_linker():
    """Return (id_resolver, distinctive_regex) over the EXISTING vault nodes.

    Existing nodes = Contract-Graph notes written by #1 + code nodes by #2. We
    link day-logs into the *knowledge* nodes (not the code/doc/devlog ones), via
    two channels: explicit id tokens, and distinctive whole-word node names.
    """
    stems = {p.stem for p in VAULT.glob("*.md")}
    knowledge = {s for s in stems if not s.startswith(_PREFIXES)}

    def resolve_id(tok):
        cand = tok.rstrip(".,;:)")
        if (VAULT / f"{cand}.md").exists():
            return cand
        if cand.startswith("KU-"):  # code/legacy alias -> KB-x.y
            kb = "KB-" + cand[3:]
            if (VAULT / f"{kb}.md").exists():
                return kb
        return None

    distinct = [s for s in knowledge
                if " " not in s and len(s) >= 6 and re.search(r"[\d_]", s)]
    distinct.sort(key=len, reverse=True)  # prefer longest match
    dist_re = (re.compile(r"\b(" + "|".join(map(re.escape, distinct)) + r")\b")
               if distinct else None)
    return resolve_id, dist_re


def crosslinks(text, self_stem, resolve_id, dist_re):
    found = []
    seen = set()

    def add(name):
        if name and name != self_stem and name not in seen:
            seen.add(name)
            found.append(name)

    for tok in ID_RE.findall(text):
        add(resolve_id(tok))
    if dist_re:
        for m in dist_re.findall(text):
            add(m)
    return found[:MAX_LINKS_PER_LOG]


# -------------------------------------------------------------------------- main
def main():
    if not VAULT.exists():
        raise SystemExit("run notion_to_obsidian.py first (vault missing)")
    tok = get_token()
    resolve_id, dist_re = build_linker()

    print("reading Dev Logs board (page + child day-logs) ...", flush=True)
    top = get_children(DEVLOGS_PAGE, tok)

    # split top-level: child_page blocks = day-logs; everything else = hub/status body
    daylogs = {}        # page_id (no dashes) -> title
    table_ids = []
    hub_blocks = []
    for b in top:
        if b["type"] == "child_page":
            daylogs[b["id"].replace("-", "")] = b["child_page"]["title"]
        elif b["type"] == "table":
            table_ids.append(b["id"])
        else:
            hub_blocks.append(b)
    print(f"  {len(daylogs)} day-log pages, {len(table_ids)} status tables")

    n_notes = n_edges = 0

    # --- DL_Status_Board: render the board/open-items tables ----------------
    if table_ids:
        sb_lines = ["---", "type: DevLog", f"notion_id: {DEVLOGS_PAGE}",
                    "kind: status-board", "---", "",
                    "# Phase 1 — Status Board & Open Items", "",
                    f"🔗 [Open in Notion](https://www.notion.so/{DEVLOGS_PAGE})", ""]
        for tid in table_ids:
            sb_lines += render_table(tid, tok)
        text = "\n".join(sb_lines)
        links = crosslinks(text, "DL_Status_Board", resolve_id, dist_re)
        if links:
            sb_lines += ["", "relates:: " + " ".join(f"[[{l}]]" for l in links)]
            n_edges += len(links)
        sb_lines += ["", "partof:: [[DL_Dev_Logs_Hub]]"]
        (VAULT / "DL_Status_Board.md").write_text("\n".join(sb_lines) + "\n",
                                                  encoding="utf-8")
        n_notes += 1

    # --- DL_<day-log> nodes -------------------------------------------------
    # process discovered nested child_pages too (worklist), not just top level
    pending = dict(daylogs)
    done = set()
    while pending:
        pid, title = pending.popitem()
        if pid in done:
            continue
        done.add(pid)
        stem = daylog_stem(title)
        # disambiguate filename collisions
        base, i = stem, 2
        while (VAULT / f"{stem}.md").exists():
            stem = f"{base}_{i}"; i += 1

        discovered = {}
        body = render(get_children(pid, tok), tok, discovered)
        for npid, ntitle in discovered.items():
            if npid not in done:
                pending[npid] = ntitle

        text = "\n".join(body)
        fm = {"type": "DevLog", "notion_id": pid}
        fm.update(extract_meta(title))
        out = ["---"] + [f"{k}: {v}" for k, v in fm.items()] + ["---", "",
               f"# {title}", "",
               f"🔗 [Open in Notion](https://www.notion.so/{pid})", ""]
        out += body
        links = crosslinks(text, stem, resolve_id, dist_re)
        out += ["", "partof:: [[DL_Dev_Logs_Hub]]"]
        if links:
            out += ["relates:: " + " ".join(f"[[{l}]]" for l in links)]
            n_edges += len(links)
        n_edges += 1  # partof edge
        (VAULT / f"{stem}.md").write_text("\n".join(out) + "\n", encoding="utf-8")
        n_notes += 1

    # --- DL_Dev_Logs_Hub: parent prose + index of every day-log -------------
    hub_discovered = {}
    hub_body = render(hub_blocks, tok, hub_discovered)
    hub = ["---", "type: DevLog", f"notion_id: {DEVLOGS_PAGE}",
           "kind: hub", "---", "",
           "# Development Logs & Reviews (hub)", "",
           f"🔗 [Open in Notion](https://www.notion.so/{DEVLOGS_PAGE})", ""]
    hub += hub_body
    hub += ["", "## Day-logs", ""]
    for pid in done:
        # rebuild stem from title; resolve actual file (handles disambiguation)
        title = daylogs.get(pid) or hub_discovered.get(pid) or pid
        st = daylog_stem(title)
        if not (VAULT / f"{st}.md").exists():
            # find disambiguated variant
            cand = sorted(VAULT.glob(f"{st}_*.md"))
            st = cand[0].stem if cand else st
        hub.append(f"- [[{st}]]")
        n_edges += 1
    if table_ids:
        hub += ["", "related:: [[DL_Status_Board]]"]
        n_edges += 1
    (VAULT / "DL_Dev_Logs_Hub.md").write_text("\n".join(hub) + "\n", encoding="utf-8")
    n_notes += 1

    # --- extend graph.json with the DevLog color group ----------------------
    gj = VAULT / ".obsidian" / "graph.json"
    g = json.loads(gj.read_text())
    q = '["type":"DevLog"]'
    if q not in {grp["query"] for grp in g["colorGroups"]}:
        g["colorGroups"].append({"query": q, "color": {"a": 1, "rgb": DEVLOG_COLOR}})
    gj.write_text(json.dumps(g, indent=2), encoding="utf-8")

    print(f"added {n_notes} Dev-Log nodes, {n_edges} edges "
          f"({len(done)} day-logs + hub + status board)")
    print("graph.json color group extended: DevLog=orange")


if __name__ == "__main__":
    main()
