r"""Pure-NumPy acceptance oracle for the RESTING cortical-tension balance (candidate 1 mechanism proof).

This oracle answers the single question the resting-baseline diagnosis
(``docs/v2_audit/RESTING_BASELINE_DIAGNOSIS_2026-07-23c.md``) left open: does an ACTIVE cortical tension —
generated by bound myosin loaded on the actin network — reduce the membrane projected residual when it is
TRANSMITTED to the membrane through explicit (force-carrying) ERM springs, WITHOUT any counterproductive ERM
preload?  It composes the same conservative force families the production cell composes, on a coarse coupled
two-shell mesh that a plain relaxation can actually equilibrate (the native solver cannot — §4 of the
diagnosis), and measures the membrane residual with the cortical tension ON vs OFF.

Composed families (all conservative / mechanistic — NO lumped surface stress):
  * turgor — a uniform internal pressure ``ΔP`` on the CLOSED membrane mesh, applied as the exact conservative
    load ``f_i = ΔP·∂V/∂x_i`` (the same volume-gradient the nucleoplasm/pressure kernels use).
  * membrane area tension γ_mem — the exact area-gradient ``f_i = −γ_mem·½·(n̂ × e_opp)`` (a bit-for-formula
    twin of ``ff.membrane_surface.membrane_area_kernel``).  Supports the Young-Laplace ``2γ_mem/R`` only.
  * ERM — RADIAL, unilateral Hookean springs membrane_i ↔ cortex_i, rest = the REAL membrane-cortex separation
    (force-free at build, NOT preloaded).  Carries tension only when stretched (ezrin cannot push).
  * cortex active myosin — a fraction ``φ`` of the cortex edges are explicit CONTRACTILE dipoles, each pulling
    its two endpoints together with a per-dipole tension derived from the resting per-head force (the discrete,
    label-blind active-tension source; its γ is read back by the method-of-planes estimator, never imposed).
  * cortex passive connectivity — soft Hookean crosslinks (rest = build length, force-free at t0).  Deliberately
    weak: the diagnosis §3 proved the sparse Hookean crosslink cortex CANNOT carry balanced resting hoop tension
    on its own, so it must NOT be the thing that holds the turgor here — the active myosin must.

The mechanism (why the residual drops): the active hoop tension CONTRACTS the cortex inward; that increases the
membrane-cortex gap, STRETCHES the radial ERM, and the ERM then pulls the membrane inward against its turgor —
exactly the ``T_cortex = ΔP·R/2 − γ_mem`` Laplace balance (§5).  With myosin OFF the cortex cannot hold, the ERM
never stretches, and the membrane carries the full turgor (the ~0.64 pN/node floor).

The fraction and per-head force are PI-GAPs; this oracle uses a TEST tension purely to prove the mechanism, and
reports the emergent cortical γ so the reduction can be read against the Laplace target.  It NEVER claims the
native gate.

Units: FF µm·pN·s.  γ in pN/µm; forces in pN; ΔP in Pa (= pN/µm²).
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np
import numpy.typing as npt

from aleph.components.incumbent.cortical_tension import measure_cortical_stress

__all__ = [
    "RestingBalanceResult",
    "icosphere",
    "coupled_resting_balance",
]


# ── coarse icosphere (pure NumPy; the two shells share directions so the ERM is exactly radial) ─────
def icosphere(subdivisions: int) -> tuple[npt.NDArray[np.float64], npt.NDArray[np.int64], npt.NDArray[np.int64]]:
    """Unit icosphere → (verts (N,3), faces (F,3), edges (E,2)); recursive midpoint subdivision."""
    t = (1.0 + 5.0**0.5) / 2.0
    verts = np.array(
        [(-1, t, 0), (1, t, 0), (-1, -t, 0), (1, -t, 0), (0, -1, t), (0, 1, t), (0, -1, -t), (0, 1, -t),
         (t, 0, -1), (t, 0, 1), (-t, 0, -1), (-t, 0, 1)], dtype=np.float64)
    faces = np.array(
        [(0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11), (1, 5, 9), (5, 11, 4), (11, 10, 2),
         (10, 7, 6), (7, 1, 8), (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9), (4, 9, 5),
         (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)], dtype=np.int64)
    verts /= np.linalg.norm(verts, axis=1, keepdims=True)
    for _ in range(int(subdivisions)):
        cache: dict[tuple[int, int], int] = {}
        vlist = list(verts)
        new_faces = []

        def midpoint(a: int, b: int) -> int:
            key = (min(a, b), max(a, b))
            if key in cache:
                return cache[key]
            m = 0.5 * (vlist[a] + vlist[b])
            m /= np.linalg.norm(m)
            vlist.append(m)
            cache[key] = len(vlist) - 1
            return cache[key]

        for i, j, k in faces:
            a, b, c = midpoint(i, j), midpoint(j, k), midpoint(k, i)
            new_faces += [(i, a, c), (a, j, b), (c, b, k), (a, b, c)]
        verts = np.array(vlist, dtype=np.float64)
        faces = np.array(new_faces, dtype=np.int64)
    edge_set = set()
    for i, j, k in faces:
        for a, b in ((i, j), (j, k), (k, i)):
            edge_set.add((min(a, b), max(a, b)))
    edges = np.array(sorted(edge_set), dtype=np.int64)
    return verts, faces, edges


# ── conservative force families (host twins of the production kernels) ──────────────────────────────
def _volume_gradient(pos: npt.NDArray, faces: npt.NDArray) -> npt.NDArray:
    """``∂V/∂x_i`` for the closed mesh — the area-weighted outward normal (nucleoplasm/pressure gradient)."""
    g = np.zeros_like(pos)
    p0, p1, p2 = pos[faces[:, 0]], pos[faces[:, 1]], pos[faces[:, 2]]
    np.add.at(g, faces[:, 0], np.cross(p1, p2) / 6.0)
    np.add.at(g, faces[:, 1], np.cross(p2, p0) / 6.0)
    np.add.at(g, faces[:, 2], np.cross(p0, p1) / 6.0)
    return g


def _area_gradient_force(pos: npt.NDArray, faces: npt.NDArray, gamma: float) -> npt.NDArray:
    """Membrane area tension ``f_i = −γ·½·(n̂ × e_opp)`` (twin of ``membrane_area_kernel``)."""
    f = np.zeros_like(pos)
    p0, p1, p2 = pos[faces[:, 0]], pos[faces[:, 1]], pos[faces[:, 2]]
    nrm = np.cross(p1 - p0, p2 - p0)
    nlen = np.linalg.norm(nrm, axis=1, keepdims=True)
    nhat = np.divide(nrm, nlen, out=np.zeros_like(nrm), where=nlen > 1e-30)
    np.add.at(f, faces[:, 0], -gamma * 0.5 * np.cross(nhat, p2 - p1))
    np.add.at(f, faces[:, 1], -gamma * 0.5 * np.cross(nhat, p0 - p2))
    np.add.at(f, faces[:, 2], -gamma * 0.5 * np.cross(nhat, p1 - p0))
    return f


def _spring_force(pos: npt.NDArray, edges: npt.NDArray, k: float, rest: npt.NDArray,
                  *, unilateral: bool = False) -> npt.NDArray:
    """Hookean edge springs ``F = k(|r|−r0) r̂`` (unilateral → tension-only, ezrin cannot push)."""
    f = np.zeros_like(pos)
    if edges.shape[0] == 0:
        return f
    d = pos[edges[:, 1]] - pos[edges[:, 0]]
    length = np.linalg.norm(d, axis=1)
    ok = length > 1e-12
    tension = k * (length - rest)
    if unilateral:
        tension = np.where(tension > 0.0, tension, 0.0)
    fmag = np.zeros_like(length)
    fmag[ok] = tension[ok] / length[ok]
    fe = fmag[:, None] * d
    np.add.at(f, edges[:, 0], fe)
    np.add.at(f, edges[:, 1], -fe)
    return f


def _dipole_force(pos: npt.NDArray, dipoles: npt.NDArray, tension: npt.NDArray) -> npt.NDArray:
    """Contractile myosin dipoles: each pulls its two endpoints together with the given tension [pN]."""
    f = np.zeros_like(pos)
    if dipoles.shape[0] == 0:
        return f
    d = pos[dipoles[:, 1]] - pos[dipoles[:, 0]]
    length = np.linalg.norm(d, axis=1)
    ok = length > 1e-12
    fmag = np.zeros_like(length)
    fmag[ok] = tension[ok] / length[ok]
    fe = fmag[:, None] * d       # pulls endpoint 0 toward endpoint 1 (contraction)
    np.add.at(f, dipoles[:, 0], fe)
    np.add.at(f, dipoles[:, 1], -fe)
    return f


@dataclass(frozen=True)
class RestingBalanceResult:
    """Membrane residual + emergent cortical tension for one (ON/OFF) resting composition."""

    myosin_on: bool
    dipole_fraction: float
    per_dipole_tension_pn: float
    gamma_cortex_pn_per_um: float
    gamma_laplace_target_pn_per_um: float
    turgor_per_node_pn: float
    membrane_residual_max_pn: float
    membrane_residual_mean_pn: float
    erm_mean_tension_pn: float
    cortex_radial_contraction_um: float
    n_membrane: int
    n_cortex_dipoles: int
    iterations: int


def coupled_resting_balance(
    *,
    dp_pa: float = 40.0,
    r_mem_um: float = 7.5,
    gap_um: float = 0.10,
    gamma_mem_pn_per_um: float = 10.0,
    k_erm_pn_per_um: float = 4.6e3,
    k_cortex_passive_pn_per_um: float = 0.0,
    dipole_fraction: float = 0.0,
    per_dipole_tension_pn: float = 0.0,
    subdivisions: int = 3,
    iterations: int = 20000,
    myosin_on: bool | None = None,
) -> RestingBalanceResult:
    r"""Compose the resting shell and report the membrane residual at the physiological setpoint.

    The membrane is HELD at its measured physiological radius ``r_mem_um`` (Wagner 2011 MCF7; the cell IS this
    size at rest — the gate asks whether the composed forces balance THERE, not where an unheld shell drifts to).
    Only the CORTEX relaxes (breathing radial mode — spherically symmetric, so it is stable and cannot collapse
    to a point), contracting under its active myosin tension until the tension balances the radial ERM it has
    stretched.  The membrane residual is then the net per-node force at the setpoint.

    * myosin OFF (``dipole_fraction=0`` or ``per_dipole_tension_pn=0``): the cortex has NO resting tension
      source (§3: passive crosslinks cannot carry balanced hoop tension → ``k_cortex_passive`` defaults 0), so it
      never contracts, the ERM stays force-free, and the membrane carries the FULL turgor floor
      ``(ΔP − 2γ_mem/R)·A_node``.
    * myosin ON: the active hoop tension contracts the cortex, stretches the radial ERM, and the transmitted
      pull cancels the membrane turgor — the residual drops toward the gate, reaching ~0 when the emergent
      cortical γ hits the Laplace target ``ΔP·R/2 − γ_mem``.

    ``per_dipole_tension_pn`` is the TEST cortical-tension knob (a stand-in for the PI-GAP fraction × per-head
    force); it is NOT a physiological datum and this oracle never claims the native gate.  Returns a
    :class:`RestingBalanceResult`.  The per-node turgor scales with the mesh (``A_node = 4πR²/N``); the native
    subdiv-6 shell (40,962 nodes) is where it equals the diagnosis's 0.644 pN — the MECHANISM (residual → 0 at
    the Laplace target) is mesh-independent, so a coarse mesh suffices for the proof.
    """
    on = (dipole_fraction > 0.0 and per_dipole_tension_pn > 0.0) if myosin_on is None else bool(myosin_on)
    r_cortex0 = r_mem_um - gap_um

    verts, faces, edges = icosphere(subdivisions)
    n = verts.shape[0]
    u_hat = verts / np.linalg.norm(verts, axis=1, keepdims=True)   # per-node radial directions
    mem = verts * r_mem_um                                         # HELD at the physiological setpoint

    a_node = 4.0 * np.pi * r_mem_um**2 / n
    turgor_per_node = float(dp_pa * a_node)
    erm_rest = np.full(n, gap_um, np.float64)                      # rest = real separation (NOT preloaded)
    cor_rest = np.linalg.norm((verts * r_cortex0)[edges[:, 1]] - (verts * r_cortex0)[edges[:, 0]], axis=1)

    # active myosin dipoles: a deterministic fraction of the cortex edges, each carrying per_dipole_tension.
    n_edges = edges.shape[0]
    if on:
        n_dip = int(np.floor(dipole_fraction * n_edges + 0.5))
        pick = np.floor((np.arange(max(n_dip, 0), dtype=np.float64) + 0.5) * n_edges / max(n_dip, 1)).astype(np.int64)
        dipoles = edges[np.unique(pick)] if n_dip > 0 else np.zeros((0, 2), np.int64)
        dip_tension = np.full(dipoles.shape[0], per_dipole_tension_pn, np.float64)
    else:
        dipoles = np.zeros((0, 2), np.int64)
        dip_tension = np.zeros(0, np.float64)

    def erm_tension(cor: npt.NDArray) -> npt.NDArray:
        stretch = np.linalg.norm(mem - cor, axis=1) - erm_rest
        return np.where(stretch > 0.0, k_erm_pn_per_um * stretch, 0.0)   # unilateral (ezrin cannot push)

    def cortex_force(cor: npt.NDArray) -> npt.NDArray:
        f = _spring_force(cor, edges, k_cortex_passive_pn_per_um, cor_rest)   # passive connectivity (default off)
        f += _dipole_force(cor, dipoles, dip_tension)                        # active hoop tension (inward)
        d = mem - cor
        length = np.linalg.norm(d, axis=1)
        u = np.divide(d, length[:, None], out=np.zeros_like(d), where=length[:, None] > 1e-12)
        f += erm_tension(cor)[:, None] * u                                   # ERM pulls cortex toward membrane
        return f

    def membrane_residual(cor: npt.NDArray) -> npt.NDArray:
        f = dp_pa * _volume_gradient(mem, faces)                # turgor (outward)
        f += _area_gradient_force(mem, faces, gamma_mem_pn_per_um)  # area tension (inward)
        d = cor - mem
        length = np.linalg.norm(d, axis=1)
        u = np.divide(d, length[:, None], out=np.zeros_like(d), where=length[:, None] > 1e-12)
        f += erm_tension(cor)[:, None] * u                      # ERM pulls membrane toward cortex (inward)
        return f

    # Breathing-mode radial relaxation of the cortex (single scalar radius; spherically symmetric ⇒ stable).
    kmax = max(k_erm_pn_per_um, k_cortex_passive_pn_per_um, 1.0)
    dt = 0.5 / kmax
    r_c = r_cortex0
    for _ in range(int(iterations)):
        cor = u_hat * r_c
        fc = cortex_force(cor)
        dr = float(np.mean(np.einsum("ij,ij->i", fc, u_hat)))   # radial-projected mean cortex force
        r_c = max(0.5 * r_cortex0, r_c + dt * dr)               # never through the centre

    cor = u_hat * r_c
    res_mag = np.linalg.norm(membrane_residual(cor), axis=1)

    # emergent cortical tension (method-of-planes, label-blind): active dipoles + passive crosslink tensions.
    families: dict = {}
    if dipoles.shape[0]:
        families["crossbridge"] = (cor[dipoles[:, 0]], cor[dipoles[:, 1]], dip_tension.copy())
    clen = np.linalg.norm(cor[edges[:, 1]] - cor[edges[:, 0]], axis=1)
    families["crosslink"] = (cor[edges[:, 0]], cor[edges[:, 1]], k_cortex_passive_pn_per_um * (clen - cor_rest))
    report = measure_cortical_stress(r_c, families, cor, np.zeros_like(cor), n_planes=32)

    return RestingBalanceResult(
        myosin_on=on,
        dipole_fraction=float(dipole_fraction if on else 0.0),
        per_dipole_tension_pn=float(per_dipole_tension_pn if on else 0.0),
        gamma_cortex_pn_per_um=float(report.gamma_total_pn_per_um),
        gamma_laplace_target_pn_per_um=float(dp_pa * r_mem_um / 2.0 - gamma_mem_pn_per_um),
        turgor_per_node_pn=turgor_per_node,
        membrane_residual_max_pn=float(res_mag.max()),
        membrane_residual_mean_pn=float(res_mag.mean()),
        erm_mean_tension_pn=float(erm_tension(cor).mean()),
        cortex_radial_contraction_um=float(r_cortex0 - r_c),
        n_membrane=n,
        n_cortex_dipoles=int(dipoles.shape[0]),
        iterations=int(iterations),
    )
