#!/usr/bin/env python
"""Regenerate `ports/ledger/INDEX.md` from the ledger entries on disk.

The index is generated rather than hand-maintained because several build lanes write ledger
entries concurrently. A hand-maintained list goes stale within the hour and is then worse than no
list at all, because it still looks authoritative.

This module is also the single parser for ledger entries: `tests/ports/test_port_discipline.py`
imports it rather than re-implementing the field extraction, so the index and the discipline tests
can never disagree about what an entry says.

Usage
-----
    python ports/regenerate_index.py            # rewrite ledger/INDEX.md
    python ports/regenerate_index.py --check    # exit 1 if the committed index is stale
    python ports/regenerate_index.py --report   # human-readable field-coverage report

Parsing philosophy
------------------
Entries are prose written by different lanes at different hours, so the parser is *tolerant about
phrasing and strict about substance*. It accepts several spellings of each field (``Aleph API`` /
``Aleph target`` / ``Target``) but does not accept a field being absent. Where it cannot parse an
entry it says so in the index rather than dropping the row — a silently missing row is the failure
mode this file exists to prevent.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
LEDGER_DIR = REPO_ROOT / "ports" / "ledger"
INDEX_PATH = LEDGER_DIR / "INDEX.md"

GENERATED_BANNER = "<!-- GENERATED by ports/regenerate_index.py — do not hand-edit. -->"

#: Entries renamed on 2026-07-30 when the ledger settled on one filename convention
#: (`ALEPH-PORT-NNN-slug.md`, lane number as the hundreds digit). Recorded here rather than
#: dropped, because other files cite the old identifiers and a reader who follows a stale
#: reference must land somewhere that tells them what happened.
RENAMED_ENTRIES: tuple[tuple[str, str], ...] = (
    ("L3-001", "ALEPH-PORT-301"),
    ("L3-002", "ALEPH-PORT-302"),
    ("L3-003", "ALEPH-PORT-303"),
    ("L3-004", "ALEPH-PORT-304"),
    ("L3-005", "ALEPH-PORT-305"),
    ("L6-001", "ALEPH-PORT-601"),
    ("L6-002", "ALEPH-PORT-602"),
    ("L6-003", "ALEPH-PORT-603"),
)


# --------------------------------------------------------------------------------------------
# Status vocabulary
# --------------------------------------------------------------------------------------------
#: Canonical states. `LANDED` is a legacy alias for `ACCEPTED` used by entries written before this
#: vocabulary existed; it is recognised, mapped, and reported as such rather than quietly renamed,
#: because rewriting another lane's status row would be editing their record.
CANONICAL_STATUSES = ("PROPOSED", "AUDITED", "ACCEPTED", "REJECTED")
STATUS_ALIASES = {"LANDED": "ACCEPTED"}

#: Statuses that assert Aleph code has landed. These carry the control obligations.
CODE_LANDED_STATUSES = ("ACCEPTED",)


# --------------------------------------------------------------------------------------------
# Mandatory fields — master plan §6, in the order the template presents them
# --------------------------------------------------------------------------------------------
@dataclass(frozen=True)
class FieldSpec:
    key: str
    human: str
    patterns: tuple[str, ...]

    def find(self, text: str) -> int | None:
        """Return the 1-based line number of the first match, or None."""
        for pat in self.patterns:
            m = re.search(pat, text, re.IGNORECASE | re.MULTILINE)
            if m is not None:
                return text.count("\n", 0, m.start()) + 1
        return None


MANDATORY_FIELDS: tuple[FieldSpec, ...] = (
    FieldSpec(
        "port_id", "Aleph port ID",
        (r"^#\s+\S+", r"\bport\s*id\b"),
    ),
    FieldSpec(
        "aleph_api", "intended Aleph API",
        (r"\bAleph\s+(API|target|module|surface)\b", r"^\|\s*Target\s*\|",
         r"\baleph/[a-z_]+/", r"\bvalidation/[a-z_]+/"),
    ),
    FieldSpec(
        "source_identity", "source repository identity",
        (r"\bffn_cellsim\b", r"\bsource\s+repo", r"\breference\s+(read|consulted)\b"),
    ),
    FieldSpec(
        "source_commit", "immutable source commit",
        (r"\b[0-9a-f]{8}(?:[0-9a-f]{32})?\b(?![0-9a-zA-Z])", r"\bcommit\b"),
    ),
    FieldSpec(
        "source_path", "source path and symbol",
        (r"ffn_sim/[\w/]+\.py", r"\bsource\s+(path|symbol)"),
    ),
    # "RE-DERIVED" / "nothing was ported" is a complete answer to this field: it says clean-room
    # won. The field asks *why source-derived porting beats clean-room*, and "it does not" is a
    # legitimate — indeed the default — answer, so the matcher accepts it.
    FieldSpec(
        "why_not_cleanroom", "why source-derived porting beats clean-room",
        (r"clean[\s\-]?room", r"\bwhy\s+port", r"\bwhy\s+porting\b",
         r"\bwhat\s+was\s+(taken|NOT\s+taken)\b", r"\bRE-?DERIVED\b",
         r"\bnothing\s+(was\s+)?(ported|taken)\b", r"\bfrom\s+scratch\b",
         r"\bno\s+code\s+(was\s+)?(ported|taken)\b"),
    ),
    FieldSpec(
        "law", "physical or mathematical law represented",
        (r"\blaw\b", r"\bderivation\b", r"\bre-?derived\b", r"\btheorem\b", r"\bidentity\b"),
    ),
    FieldSpec(
        "units_domains_invariants", "units, domains, singular cases, invariants",
        (r"\binvariant", r"\bunits?\b.{0,40}\bdomain", r"^##.*\bunits\b", r"\bsingular\b"),
    ),
    FieldSpec(
        "evidence_class", "source evidence class and known retractions",
        (r"\bevidence\s+class\b", r"\bretract", r"\bclassification\b", r"\bport\s+class\b",
         r"\bevidence\b"),
    ),
    FieldSpec(
        "independent_oracle", "independent oracle or derivation",
        (r"\boracle\b", r"\bindependent\s+(derivation|check|oracle|verification)\b",
         r"^##.*\bindependen", r"\bre-?derived\b"),
    ),
    FieldSpec(
        "positive_control", "positive control",
        (r"\bpositive\b[^\n]{0,60}\bcontrol\b", r"\bcontrol\b[^\n]{0,60}\bpositive\b",
         r"^\|\s*Positive\b"),
    ),
    FieldSpec(
        "negative_control", "deliberately failing negative control",
        (r"\bnegative\b[^\n]{0,60}\b(control|must\s+fail)\b",
         r"\bcontrol\b[^\n]{0,60}\bnegative\b",
         r"^\|\s*Negative\b", r"\bcounterexample\b"),
    ),
    FieldSpec(
        "numerical_envelope", "numerical and precision envelope",
        (r"\bprecision\b", r"\btoleranc", r"\bULP\b", r"\bfloat(32|64)\b",
         r"\bround[\s\-]?off\b", r"\bnumerical\b"),
    ),
    FieldSpec(
        "residency", "production-backend residency and transfer",
        (r"\bresidenc", r"\bbackend\b", r"\bdevice\b", r"\bGPU\b", r"\bhost[\s\-]side\b",
         r"\bCPU\b", r"\btransfer\b"),
    ),
    FieldSpec(
        "discarded_prose", "comments and docstrings to discard",
        (r"\bstrip(ped|ping)?\b", r"\bdiscard", r"\bdocstring", r"\bcomments?\b",
         r"\bnew\s+prose\b"),
    ),
    FieldSpec(
        "acceptance", "acceptance result, reviewer, rollback",
        (r"\bacceptance\b", r"\breviewer\b", r"\brollback\b", r"\bstatus\b"),
    ),
)

#: Tokens that mean "this field was not actually filled in".
PLACEHOLDER_PATTERNS: tuple[tuple[str, str], ...] = (
    (r"\bTODO\b", "TODO"),
    (r"\bTBD\b", "TBD"),
    (r"\bFIXME\b", "FIXME"),
    (r"\bXXX\b", "XXX"),
    (r"\?{3,}", "???"),
    (r"\bPLACEHOLDER\b", "PLACEHOLDER"),
    (r"<fill[\s_\-]?in", "<fill in>"),
)

_INLINE_CODE = re.compile(r"`[^`]*`")


def strip_inline_code(line: str) -> str:
    """Remove inline-code spans before scanning for placeholders.

    A placeholder inside backticks is a *citation* of a marker that lives somewhere else —
    ``see the `TODO(L1)` in validation/analytic/dimensions.py`` is a filled-in field that happens
    to mention an unfilled thing elsewhere. A bare ``TODO`` is an unfilled field. The distinction
    is small and it is the difference between the check being useful and being noise.
    """
    return _INLINE_CODE.sub(" ", line)


#: A control line is only credible if it names a test. Prose that says "we have controls" is not a
#: control. Matches `test_foo`, `path/test_x.py::test_y`, and `...::test_y`.
TEST_REFERENCE = re.compile(r"\btest_[A-Za-z0-9_]+")


# --------------------------------------------------------------------------------------------
# Entry model
# --------------------------------------------------------------------------------------------
@dataclass
class LedgerEntry:
    path: Path
    text: str
    title: str = ""
    port_id: str = ""
    lane: str = ""
    raw_status: str = ""
    status: str = "UNKNOWN"
    aleph_targets: tuple[str, ...] = ()
    source_commit: str = ""
    found_fields: dict[str, int] = field(default_factory=dict)
    missing_fields: tuple[str, ...] = ()
    placeholders: tuple[tuple[int, str], ...] = ()
    positive_control_line: int | None = None
    negative_control_line: int | None = None

    @property
    def rel(self) -> str:
        return self.path.relative_to(REPO_ROOT).as_posix()

    @property
    def code_has_landed(self) -> bool:
        return self.status in CODE_LANDED_STATUSES

    @property
    def status_display(self) -> str:
        if self.raw_status and self.raw_status.upper() in STATUS_ALIASES:
            return f"{self.status} (via {self.raw_status.upper()})"
        return self.status


_TABLE_ROW = re.compile(r"^\|\s*([^|]+?)\s*\|\s*(.*?)\s*\|\s*$", re.MULTILINE)
_ALEPH_TARGET = re.compile(r"\b((?:aleph|validation)/[A-Za-z0-9_/]+\.py)")
_SHA = re.compile(r"\b([0-9a-f]{40}|[0-9a-f]{8})\b")


def _table_lookup(text: str, *names: str) -> str:
    """First value of a `| Field | Value |` row whose label matches any of `names`."""
    wanted = {n.lower() for n in names}
    for m in _TABLE_ROW.finditer(text):
        label = m.group(1).strip().strip("*`").lower()
        if label in wanted:
            return m.group(2).strip()
    return ""


def _find_control(text: str, kind: str) -> int | None:
    """1-based line number of a control line that names a test, or None.

    `kind` is "positive" or "negative". A negative control also matches the phrases
    "must fail" and "counterexample", which is how several lanes spell it.
    """
    if kind == "positive":
        keys = (r"\bpositive\b",)
    else:
        keys = (r"\bnegative\b", r"\bmust\s+fail\b", r"\bcounterexample\b")
    for lineno, line in enumerate(text.splitlines(), start=1):
        if not TEST_REFERENCE.search(line):
            continue
        low = line.lower()
        if any(re.search(k, low) for k in keys):
            if kind == "positive" and re.search(r"\bnegative\b", low) and not re.search(
                r"\bpositive\b", low
            ):
                continue
            return lineno
    return None


def parse_entry(path: Path) -> LedgerEntry:
    text = path.read_text(encoding="utf-8")
    entry = LedgerEntry(path=path, text=text)

    m = re.search(r"^#\s+(.*)$", text, re.MULTILINE)
    entry.title = m.group(1).strip() if m else path.stem

    entry.port_id = (
        _table_lookup(text, "aleph port id", "port id", "id")
        or re.split(r"\s+[—\-–]\s+", entry.title)[0].strip().strip("`")
        or path.stem
    )
    entry.lane = _table_lookup(text, "lane")

    raw = _table_lookup(text, "status", "state").strip().strip("*`").upper()
    entry.raw_status = raw
    if raw in CANONICAL_STATUSES:
        entry.status = raw
    elif raw in STATUS_ALIASES:
        entry.status = STATUS_ALIASES[raw]
    elif raw:
        entry.status = f"UNRECOGNISED:{raw}"
    else:
        entry.status = "UNKNOWN"

    entry.aleph_targets = tuple(dict.fromkeys(_ALEPH_TARGET.findall(text)))
    shas = _SHA.findall(text)
    entry.source_commit = max(shas, key=len) if shas else ""

    found: dict[str, int] = {}
    missing: list[str] = []
    for spec in MANDATORY_FIELDS:
        line = spec.find(text)
        if line is None:
            missing.append(spec.key)
        else:
            found[spec.key] = line
    entry.found_fields = found
    entry.missing_fields = tuple(missing)

    holders: list[tuple[int, str]] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        bare = strip_inline_code(line)
        for pat, name in PLACEHOLDER_PATTERNS:
            if re.search(pat, bare):
                holders.append((lineno, name))
    entry.placeholders = tuple(holders)

    entry.positive_control_line = _find_control(text, "positive")
    entry.negative_control_line = _find_control(text, "negative")
    return entry


def load_entries(ledger_dir: Path = LEDGER_DIR) -> list[LedgerEntry]:
    """Every ledger entry on disk, sorted by filename. INDEX.md itself is not an entry."""
    if not ledger_dir.is_dir():
        return []
    paths = sorted(p for p in ledger_dir.glob("*.md") if p.name != "INDEX.md")
    return [parse_entry(p) for p in paths]


# --------------------------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------------------------
def render_index(entries: list[LedgerEntry]) -> str:
    counts: dict[str, int] = {}
    for e in entries:
        counts[e.status] = counts.get(e.status, 0) + 1

    lines: list[str] = [
        GENERATED_BANNER,
        "",
        "# Port ledger — index",
        "",
        "Regenerate with:",
        "",
        "```sh",
        # **Neither derived from this machine nor hardcoded**, and both of those were tried.
        #
        # Hardcoding the path broke when the repository was renamed on 2026-07-30: every copy then
        # told the reader to cd into a directory that no longer existed. The fix was to interpolate
        # `REPO_ROOT`, which is derived from `__file__` — and that traded a rename bug for a worse
        # one, because this file is **checked in and compared byte-for-byte** by
        # `tests/ports/test_port_discipline.py::test_index_is_not_stale`. A generated artefact
        # containing an absolute path can only ever be current on the machine that generated it.
        # Measured 2026-07-31: identical commit, green on the author's Mac, red on the GPU host, and the
        # entire diff was `/Users/sw1/Project_Aleph` versus `/home/sungwook/Project_Aleph`.
        #
        # `git rev-parse` fixes both at once: it survives a rename *and* is the same string on every
        # machine. The interpreter is named by rule rather than by path for the same reason — the
        # line above it used to hardcode one author's home directory.
        'cd "$(git rev-parse --show-toplevel)" && python ports/regenerate_index.py',
        "```",
        "",
        "Use the interpreter `CLAUDE.md` names — never `python3`, never the reference project's env.",
        "",
        f"{len(entries)} entr{'y' if len(entries) == 1 else 'ies'}. "
        + ", ".join(f"{k}: {v}" for k, v in sorted(counts.items()))
        + ".",
        "",
        "`LANDED` is a legacy spelling of `ACCEPTED`; see `ports/README.md` §6.",
        "",
        "| Entry | Port ID | Lane | Status | Aleph target | Source commit | Controls |",
        "|---|---|---|---|---|---|---|",
    ]
    for e in entries:
        target = e.aleph_targets[0] if e.aleph_targets else "—"
        if len(e.aleph_targets) > 1:
            target += f" (+{len(e.aleph_targets) - 1})"
        commit = e.source_commit[:8] if e.source_commit else "—"
        pos = "P" if e.positive_control_line else "·"
        neg = "N" if e.negative_control_line else "·"
        lines.append(
            f"| [`{e.path.name}`]({e.path.name}) | `{e.port_id}` | {e.lane or '—'} | "
            f"`{e.status_display}` | `{target}` | `{commit}` | {pos}{neg} |"
        )

    incomplete = [e for e in entries if e.missing_fields or e.placeholders]
    lines += ["", "## Entries with unfilled mandatory fields", ""]
    if not incomplete:
        lines.append("None. Every entry carries every mandatory field from master plan §6.")
    else:
        for e in incomplete:
            bits = []
            if e.missing_fields:
                bits.append("missing " + ", ".join(f"`{k}`" for k in e.missing_fields))
            if e.placeholders:
                bits.append(
                    "placeholders at "
                    + ", ".join(f"L{ln} ({tok})" for ln, tok in e.placeholders[:5])
                )
            lines.append(f"- `{e.path.name}` — " + "; ".join(bits))

    unknown = [e for e in entries if e.status.startswith(("UNKNOWN", "UNRECOGNISED"))]
    lines += ["", "## Entries with no recognised status", ""]
    if not unknown:
        lines.append("None.")
    else:
        for e in unknown:
            lines.append(f"- `{e.path.name}` — `{e.status}`")

    lines += ["", "## Former identifiers", "",
              "Renamed 2026-07-30 when the ledger settled on one filename convention.",
              "", "| Former ID | Current ID |", "|---|---|"]
    for old, new in RENAMED_ENTRIES:
        lines.append(f"| `{old}` | `{new}` |")

    lines.append("")
    return "\n".join(lines)


def render_report(entries: list[LedgerEntry]) -> str:
    out: list[str] = [f"{len(entries)} ledger entries under {LEDGER_DIR}", ""]
    for e in entries:
        out.append(f"{e.path.name}")
        out.append(f"  status   : {e.status_display!r} (raw {e.raw_status!r})")
        out.append(f"  targets  : {e.aleph_targets or '—'}")
        out.append(f"  commit   : {e.source_commit or '—'}")
        out.append(f"  controls : +{e.positive_control_line} -{e.negative_control_line}")
        out.append(f"  missing  : {list(e.missing_fields) or '—'}")
        out.append(f"  placehold: {list(e.placeholders) or '—'}")
        out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit 1 if INDEX.md is stale")
    ap.add_argument("--report", action="store_true", help="print a field-coverage report")
    args = ap.parse_args(argv)

    entries = load_entries()
    if args.report:
        print(render_report(entries))
        return 0

    rendered = render_index(entries)
    if args.check:
        current = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if current != rendered:
            print(f"STALE: {INDEX_PATH} does not match the ledger. Regenerate it.", file=sys.stderr)
            return 1
        print("INDEX.md is current.")
        return 0

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(rendered, encoding="utf-8")
    print(f"wrote {INDEX_PATH} ({len(entries)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
