"""H.LINC nesprin-SUN bridge ACTIVATION GATE (LIVE, 2026-06-09).

Fourth compartment graduated EXPERIMENTAL->LIVE under the PI ownership grant.
LINC (Option A) bonds each ``nucleus_bead`` to its nearest perinuclear
``if_bead`` (the LIVE intermediate-filament cage) with a per-bond EXACT-r0
harmonic, so the nucleus is mechanically coupled to the perinuclear cytoskeleton
at the physiological operating point. The gate builds the FULL physiological
baseline cell with the IF cage ON, OFF vs ON for LINC, and checks the
build-time activation controls:

  BRIDGES FORMED  — ON forms n_bridges>0 linc_nesprin bonds (REFUTE-guard against
                    the zero-bonds-at-real-geometry trap). LINC adds ZERO
                    particles (bonds only) → particle count IDENTICAL OFF vs ON.
  FORCE-FREE      — each bridge is born at its EXACT as-built nucleus↔if_bead
                    separation → construction strain ~0 (the ~8 pN resting
                    tension is generated by actomyosin AFTER equilibration, not
                    injected at build; physiological-baseline rule).
  NO-CONTAM       — cortical γ_soft IDENTICAL OFF vs ON (linc_ bonds registry-
                    denylisted); every linc_ bond type excluded from the mask.
  OFF-IDENTITY    — LINC off reproduces the IF-cage baseline inventory exactly.
  CFL HEADROOM    — production dt ≤ linc_cfl_dt_max(k_linc, γ_bead) (analytic).

PRIMARY <T_linc> ∈ [2,10] pN resting-tension oracle (Déjardin 2020) needs an
equilibrated actomyosin run and is DEFERRED (the full-cell raw run trips the
BAOAB guard — needs the equilibration prelude, the same known full-cell issue
as the other compartments). k_linc=1e-2 N/m is the route-A folded-rod secant
(Rief 1999; ORDER, PI-pending ratification). ⚠ At the ×40 mesoscale the
nucleus↔if_bead separation is ~0.5-1.5 µm (NOT the 50 nm real nesprin span), so
r0 is an EFFECTIVE mesoscale coupling length — see PLATFORM_PI_QUEUE.

Run:  python ffn_sim/scripts/h7_linc_activation_gate.py
"""

from __future__ import annotations

import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
if str(_HERE.parents[2]) not in sys.path:
    sys.path.insert(0, str(_HERE.parents[2]))

import json
import math
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from ffn_sim.cell.compartment_registry import REGISTRY, load_recipe
from ffn_sim.cell.linc import linc_cfl_dt_max
from ffn_sim.cell.manifest import build_baseline_cell, load_manifest
from ffn_sim.cortex.cortical_tension import (
    _is_adhesion_bond_type,
    measure_cortical_tension,
)

_OUT = _HERE.parents[1] / "outputs" / "h7"


def _gamma_soft(cell) -> float:
    cell.simulation.run(0)
    r = measure_cortical_tension(
        cell.simulation, R_cell=cell.p_cortex.R_cell,
        p_enclosed_volume=cell.p_enclosed_volume,
    )
    return float(r.get("gamma_soft_N_per_m", r.get("gamma_soft", float("nan"))))


def run() -> dict:
    base = load_manifest("mcf7_baseline.yaml")
    # OFF = IF cage ON, LINC OFF; ON = LINC coupled (IF cage + LINC).
    m_off, _ = REGISTRY.compose_manifest(
        load_recipe("if_cage"), base_manifest=base, strict=True
    )
    m_on, _ = REGISTRY.compose_manifest(
        load_recipe("linc_coupled"), base_manifest=base, strict=True
    )
    cell_off = build_baseline_cell("mcf7_baseline.yaml", manifest=m_off, seed=1)
    cell_on = build_baseline_cell("mcf7_baseline.yaml", manifest=m_on, seed=1)
    p = cell_on.p_linc

    s_off = cell_off.simulation.state.get_snapshot()
    s_on = cell_on.simulation.state.get_snapshot()
    n_part_delta = int(s_on.particles.N) - int(s_off.particles.N)
    n_bond_delta = int(s_on.bonds.N) - int(s_off.bonds.N)

    handles = cell_on.extras.get("handles", {})
    n_bridges = int(handles.get("n_linc_bridges", 0))
    layout = handles.get("linc_layout")
    linc_bonds = [t for t in s_on.bonds.types if t.startswith("linc_")]

    # BRIDGES FORMED + bonds-only (zero new particles).
    bridges_ok = n_bridges > 0 and n_part_delta == 0 and n_bond_delta == n_bridges

    # FORCE-FREE construction: each per-bond EXACT-r0 type is born at its as-built
    # separation. Verify the live snapshot separations match the layout r0 (the
    # registered rest lengths) to ~0 strain.
    max_strain = float("nan")
    if layout is not None and n_bridges > 0:
        pos = np.asarray(s_on.particles.position, dtype=np.float64)
        pairs = np.asarray(layout.pairs, dtype=np.int64)
        sep = np.linalg.norm(pos[pairs[:, 0]] - pos[pairs[:, 1]], axis=1)
        r0 = np.asarray(layout.r0, dtype=np.float64)
        max_strain = float(np.max(np.abs(sep - r0) / np.maximum(r0, 1e-30)))
    force_free_ok = bool(np.isfinite(max_strain) and max_strain < 1e-6)

    # NO-CONTAMINATION: cortical γ_soft identical OFF vs ON; mask excludes linc_.
    mask_excludes_linc = all(_is_adhesion_bond_type(t) for t in linc_bonds)
    g_off, g_on = _gamma_soft(cell_off), _gamma_soft(cell_on)
    gamma_identical = bool(
        np.isfinite(g_off) and np.isfinite(g_on)
        and abs(g_on - g_off) <= 1e-12 * max(1.0, abs(g_off))
    )

    # CFL HEADROOM (analytic): production dt vs the LINC overdamped CFL gate.
    _ig = cell_on.simulation.operations.integrator
    dt_prod = float(getattr(_ig, "dt", 0.0) or 0.0)
    # Per-bead drag on the bonded nucleus/if beads at cytoplasm viscosity.
    eta = float(getattr(cell_on.p_cytoplasm, "eta_eff", 65.9))
    R_if_bead = 0.5 * float(cell_on.p_intermediate_filaments.d_if)
    gamma_bead = 6.0 * math.pi * eta * R_if_bead
    dt_cfl = linc_cfl_dt_max(float(p.k_linc), gamma_bead)
    cfl_ok = bool(dt_prod <= dt_cfl) if dt_prod > 0 else True

    ok = (
        bridges_ok and force_free_ok and mask_excludes_linc
        and gamma_identical and cfl_ok
    )

    result = {
        "gate": "H.LINC linc activation",
        "verdict": "PASS" if ok else "REVIEW",
        "physics_claim": True,
        "params": {
            "k_linc_Npm": float(p.k_linc), "r0_default_m": float(p.r0),
            "capture_radius_m": float(p.capture_radius),
            "n_bridges_max": int(p.n_bridges_max),
            "f_rest_oracle_pN": float(p.f_rest) * 1e12,
        },
        "controls": {
            "bridges_formed": bool(bridges_ok),
            "n_linc_bridges": n_bridges,
            "n_linc_bond_types": len(linc_bonds),
            "n_particle_delta": n_part_delta,    # MUST be 0 (bonds only)
            "n_bond_delta": n_bond_delta,
            "force_free_construction": {
                "ok": force_free_ok, "max_strain": max_strain,
            },
            "no_contamination": {
                "mask_excludes_all_linc": bool(mask_excludes_linc),
                "gamma_soft_off_N_per_m": g_off,
                "gamma_soft_on_N_per_m": g_on,
                "gamma_identical": gamma_identical,
            },
            "off_identity": bool(n_part_delta == 0),
            "cfl_headroom": {
                "ok": cfl_ok, "dt_prod_s": dt_prod, "dt_cfl_max_s": dt_cfl,
                "gamma_bead_Nspm": gamma_bead,
            },
        },
        "deferred": {
            "resting_tension_oracle_pN": "[2,10] pN (Déjardin 2020) — needs an "
            "equilibrated actomyosin run; full-cell raw run trips the BAOAB guard "
            "(equilibration prelude required), same as the other compartments.",
            "k_linc_ratification": "route-A 1e-2 N/m (Rief 1999) ORDER — PI-pending.",
        },
        "note": (
            "REAL build-time activation gate on the full physiological baseline "
            "with the IF cage ON. Option A: nucleus_bead → nearest if_bead, "
            "per-bond EXACT-r0 (force-free at construction). KEY control is "
            "no-contamination: cortical γ_soft identical OFF vs ON (linc_ "
            "registry-denylisted). LINC adds ZERO particles (bonds only). The "
            "[2,10] pN resting-tension oracle is deferred (needs equilibration). "
            "⚠ mesoscale r0 ~0.5-1.5 µm ≠ 50 nm real span (PI queue)."
        ),
    }
    _figure(s_off, s_on, layout, g_off, g_on, result)
    return result


def _figure(s_off, s_on, layout, g_off, g_on, result) -> None:
    fig, (ax0, ax1, ax2) = plt.subplots(1, 3, figsize=(15, 4.4))
    pos = np.asarray(s_on.particles.position)
    tid = np.asarray(s_on.particles.typeid)
    types = list(s_on.particles.types)
    nuc_id = {i for i, t in enumerate(types) if t == "nucleus_bead"}
    if_id = {i for i, t in enumerate(types) if t == "if_bead"}
    is_nuc = np.array([t in nuc_id for t in tid])
    is_if = np.array([t in if_id for t in tid])
    other = ~(is_nuc | is_if)
    ax0.scatter(pos[other, 0] * 1e6, pos[other, 1] * 1e6, s=2, color="0.85", label="cortex")
    ax0.scatter(pos[is_nuc, 0] * 1e6, pos[is_nuc, 1] * 1e6, s=3, color="#2166ac", label="nucleus")
    ax0.scatter(pos[is_if, 0] * 1e6, pos[is_if, 1] * 1e6, s=4, color="#8c564b", label="IF cage")
    if layout is not None and layout.n_bridges > 0:
        pr = np.asarray(layout.pairs, dtype=np.int64)
        for a, b in pr:
            ax0.plot([pos[a, 0] * 1e6, pos[b, 0] * 1e6],
                     [pos[a, 1] * 1e6, pos[b, 1] * 1e6],
                     color="#d62728", lw=0.5, alpha=0.6)
    ax0.set_xlabel("x [um]"); ax0.set_ylabel("y [um]")
    ax0.set_aspect("equal", adjustable="datalim")
    ax0.set_title(f"LINC bridges nucleus↔IF ({result['controls']['n_linc_bridges']})")
    ax0.legend(fontsize=8)

    if layout is not None and layout.n_bridges > 0:
        ax1.hist(np.asarray(layout.r0) * 1e9, bins=24, color="#d62728", alpha=0.85)
        ax1.set_xlabel("linc_nesprin r0 (= as-built sep) [nm]")
        ax1.set_ylabel("count")
        ax1.set_title(
            f"per-bond EXACT-r0 (force-free; max strain "
            f"{result['controls']['force_free_construction']['max_strain']:.1e})"
        )

    ax2.bar(["γ_soft OFF", "γ_soft ON"], [g_off * 1e3, g_on * 1e3], color=["#4c72b0", "#dd8452"])
    ax2.set_ylabel("cortical γ_soft [mN/m]")
    ax2.set_title(
        f"NO-contamination: identical="
        f"{result['controls']['no_contamination']['gamma_identical']}"
    )
    fig.suptitle(
        f"H.LINC activation GATE — {result['verdict']} | "
        f"bridges={result['controls']['bridges_formed']} | "
        f"force-free={result['controls']['force_free_construction']['ok']} | "
        f"no-contam={result['controls']['no_contamination']['gamma_identical']}",
        fontsize=9.5,
    )
    (_OUT / "figs").mkdir(parents=True, exist_ok=True)
    fig.savefig(_OUT / "figs" / "h7_linc_activation_gate.png", dpi=130, bbox_inches="tight")
    plt.close(fig)


def main() -> int:
    res = run()
    (_OUT / "production").mkdir(parents=True, exist_ok=True)
    path = _OUT / "production" / "h7_linc_activation_gate.json"
    with open(path, "w") as fh:
        json.dump(res, fh, indent=2, default=str)
    c = res["controls"]; nc = c["no_contamination"]
    print(f"[H.LINC linc activation gate] {res['verdict']}")
    print(f"  bridges formed={c['bridges_formed']} (n={c['n_linc_bridges']}, "
          f"{c['n_linc_bond_types']} types, +{c['n_particle_delta']} part, +{c['n_bond_delta']} bonds)")
    print(f"  force-free: max strain={c['force_free_construction']['max_strain']:.2e} "
          f"ok={c['force_free_construction']['ok']}")
    print(f"  no-contam: γ_soft OFF={nc['gamma_soft_off_N_per_m']:.4e} ON={nc['gamma_soft_on_N_per_m']:.4e} "
          f"identical={nc['gamma_identical']}; linc excluded={nc['mask_excludes_all_linc']}")
    print(f"  cfl: dt_prod={c['cfl_headroom']['dt_prod_s']:.2e} ≤ dt_cfl={c['cfl_headroom']['dt_cfl_max_s']:.2e} "
          f"ok={c['cfl_headroom']['ok']}")
    print(f"  json: {path}")
    return 0 if res["verdict"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
