"""Ventral stress fibers — explicit contractile actomyosin bundles (KU-3.5/3.1).

ADDITIVE, DEFAULT-OFF compartment. A ventral stress fiber (vSF) is a
contractile actomyosin BUNDLE that spans focal-adhesion to focal-adhesion
along the basal (ventral) plane of an adherent cell. This module lays out
``n_SF`` such bundles as EXPLICIT particle/bond topology — there is NO lumped
"cable spring" standing in for the fiber. Each bundle is built from the SAME
fine-grained vocabulary the cortex already uses:

* an explicit chain of actin beads (``sf_actin``) along the FA→FA axis,
* explicit α-actinin crosslinker head-pairs (``sf_xlink_head``) laid down at
  a SARCOMERIC periodicity (Tojkander 2012; Hotulainen-Lappalainen 2006),
* explicit NMII bipolar minifilaments (Stam-Hocky D5 architecture, reused
  verbatim from :mod:`ffn_sim.cortex.myosin` / :mod:`ffn_sim.bridge.motor`)
  that LOAD the bundle — the contractile force is generated by explicit motor
  heads pulling on explicit actin, not by a prescribed tension.

The two endpoints of every bundle anchor onto EXISTING focal-adhesion clutch
particles (the ``integrin``/clutch beads built by :mod:`ffn_sim.bridge.fa`),
so the SF tension is transmitted into the substrate through the real FA load
path. This compartment therefore REQUIRES the ``fa`` compartment to be present
(endpoint FA-clutch tags are passed in by the Lead at wiring time).

Why this is a BASAL-PLANE observable, NOT cortical hoop γ
---------------------------------------------------------
The SF bundle carries a NON-CORTICAL, FA-to-FA load path. Its bonds are
chord-like (they cut straight across the basal plane between two adhesions),
they are NOT part of the cortical shell whose hoop stress defines the
cortical tension γ (KU-3.5). Every bond type this module creates is prefixed
``sf_`` (see :data:`GAMMA_DENYLIST_PREFIX`) so the cortical-tension estimator
(:mod:`ffn_sim.cortex.cortical_tension`) can DENYLIST it and never sum SF
tension into γ. SF contractility is reported as its own basal observable —
:func:`measure_sf_tension` returns the mean axial tension of the explicit
``sf_actin`` chain bonds, comparable to the single-SF force band below.

Explicit mechanism — what particles / bonds
-------------------------------------------
Per bundle ``b`` spanning FA endpoint ``A`` → FA endpoint ``B``:

* ``n_beads`` ``sf_actin`` beads evenly spaced on the segment A→B
  (bead spacing ``ℓ0_actin = |B−A| / (n_beads−1)``).
* ``n_beads − 1`` ``sf_actin_bond`` harmonic bonds along the chain
  (the load-bearing backbone; tension measured here).
* the two end beads carry an ``sf_anchor`` harmonic bond each, tying bead 0
  to FA endpoint ``A`` and bead ``n_beads−1`` to FA endpoint ``B``.
* α-actinin crosslinkers laid down every ``sarcomere_spacing`` along the
  bundle: an ``sf_xlink_head`` pair joined by an ``sf_xlink_intra`` bond,
  with each head tied to the nearest ``sf_actin`` bead by an ``sf_xlink_attach``
  bond (sarcomeric banding; one crosslinker per period).
* NMII minifilaments (D5 Stam-Hocky): backbone + head beads + intra bonds,
  reused from :mod:`ffn_sim.cortex.myosin`. These are appended through the
  EXISTING myosin builder so the head↔actin stepping (D6 Hill) and Bell-Evans
  D2 kinetics carry over unchanged — the myosin is the explicit force source.
  (The myosin block is OPTIONAL at this layer: this module builds the actin +
  α-actinin scaffold and the FA anchors; the Lead attaches the existing
  cortex/bridge myosin updater onto the ``sf_actin`` chain. When myosin is not
  attached the bundle is a passive elastic cable — still explicit, no lumped
  tension is injected. A ``sf_`` myosin variant is a documented TODO so the SF
  motors are denylisted distinctly from cortical motors.)

Sanity Gate
-----------
*Per CLAUDE.md Hard Rule. STATIC + analytical checks in
``ffn_sim/tests/test_stress_fibers.py``.*

1. **Dimensional analysis**
   - ``k_actin`` [N/m] · ``Δℓ`` [m] → axial tension [N]. ✓
   - ``sarcomere_spacing`` [m]; ``n_sarcomeres = round(L_bundle / spacing)``
     dimensionless. ✓
   - ``ℓ0_actin = L_bundle / (n_beads − 1)`` [m]. ✓
   - ``k_anchor`` [N/m] · anchor stretch [m] → anchor force [N]. ✓
   - Single-SF tension band ``F_SF`` [N] = ``Σ`` axial bond tensions / chain.

2. **Boundary cases**
   - ``enabled=False`` (or cfg missing / ``enabled: false``): resolver returns
     ``ResolvedStressFibers(enabled=False, ...)`` with zeros; the builder
     EARLY-RETURNS its input snapshot unchanged (0 particles, 0 bonds added).
   - ``n_SF = 0``: builder is a no-op (empty layout).
   - ``n_beads < 2``: ValueError (a bundle needs ≥ 2 beads to span A→B).
   - ``L_bundle = |B − A| = 0`` (coincident FA endpoints): ValueError at
     LAYOUT time (degenerate bundle — no axis).
   - any non-finite / ≤ 0 stiffness / spacing: ValueError at resolve time.

3. **Conservation invariants / no-net-force**
   - The ``sf_actin_bond`` and ``sf_xlink_*`` bonds are ``md.bond.Harmonic``
     pairs → Newton's 3rd law holds → the bundle injects ZERO net momentum
     internally. The ``sf_anchor`` bond is also a symmetric harmonic pair
     between bead and FA particle (no external field), so the FA↔SF coupling
     is momentum-conserving too. (Contrast ERM, which is an external radial
     field and intentionally breaks translation symmetry.)
   - Particle count added = ``Σ_b [ n_beads_b + 2·n_sarcomeres_b ]``.
   - Bond count added = ``Σ_b [ (n_beads_b − 1)  (chain)
     + 2  (two FA anchors)
     + n_sarcomeres_b·2  (xlink: 1 intra + ... )]`` — exact count asserted in
     the test (see :meth:`StressFiberLayout` docstring for the breakdown).

4. **Numerical sanity (CFL)**
   - The actin backbone stiffness ``k_actin`` sets ``τ_actin = γ_b / k_actin``.
     With ``k_actin = 1e-2 N/m`` (see Magic-Number Block) and the cortex
     per-bead drag ``γ_b ≈ 3.9e-10 N·s/m``, ``τ_actin ≈ 3.9e-8 s = 39 ns`` —
     comparable to the cortex ``dt_CFL ≈ 13 ns``, so the SF backbone is the
     stiffest element and SETS the step. :func:`stress_fiber_dt_cfl` returns
     ``cfl_safety · γ_b / k_stiffest`` so the Lead can gate ``dt`` against it
     (the anchor ``k_anchor`` is comparable; ``k_xl`` is far softer). A
     ``cfl_strict`` gate is provided in the attach helper, mirroring ERM.
   - All positions / forces float64.

5. **Sign / sense**
   - A ``sf_actin_bond`` stretched beyond its rest length ``ℓ0_actin`` pulls
     its two beads TOGETHER (toward each other / inward along the bundle axis)
     — contractile. STATIC test stretches one chain bond and asserts the force
     on the outer bead points back toward its neighbour.
   - An ``sf_anchor`` bond stretched pulls the SF end bead TOWARD its FA
     anchor (the FA transmits the pull into the substrate). STATIC test.

6. **Measurement-protocol consistency**
   - :func:`measure_sf_tension` reports the mean axial chain-bond tension
     ``T = k_actin · max(0, |Δr| − ℓ0_actin)`` over the ``sf_actin_bond``
     family of one bundle — the SAME quantity the single-SF force band probes
     (Kumar 2006 ablation tension ~10-30 nN). It is a BASAL observable, summed
     over the ``sf_`` load path, and is explicitly DENYLISTED from γ.

Compartment Performance Contract
--------------------------------
* **Particle types added**: ``sf_actin`` (backbone beads), ``sf_xlink_head``
  (α-actinin heads). (NMII reuses the existing ``cortex_myosin_*`` types via
  the shared builder; no new myosin particle type is minted here.)
* **Particle count** at ``n_SF`` bundles, ``n_beads`` per bundle,
  ``n_sarc`` α-actinin periods per bundle:
  ``n_SF · (n_beads + 2·n_sarc)``. For a representative basal layout
  (``n_SF = 20``, ``n_beads = 24`` → ~12 µm bundle at 0.5 µm spacing,
  ``n_sarc ≈ 24``): ``20·(24 + 48) = 1440`` particles — well under the ~1000
  mesoscopic cortex filaments and a small fraction of native ~38000.
  At native scale (``n_SF ≈ 50``, ``n_beads ≈ 50``, ``n_sarc ≈ 50``):
  ``50·(50 + 100) = 7500`` particles. SF is a SPARSE basal compartment.
* **Bond / angle count**: per bundle ``(n_beads − 1) + 2 + 2·n_sarc``
  harmonic bonds; NO angles (the bundle is a straight FA→FA chord; bending
  rigidity is a documented TODO). At ``n_SF=20`` above: ``20·(23+2+48)=1460``
  bonds.
* **Per-step force**: NO. This module adds bonds only; force is the standard
  ``md.bond.Harmonic`` already in the integrator (the SF contraction is driven
  by the reused myosin updater, which is per-BATCH, not per-step).
* **Per-batch updater**: only via the REUSED cortex/bridge myosin
  ``MyosinStepUpdater`` (D2 Bell-Evans + D6 Hill) when the Lead attaches it to
  the ``sf_actin`` chain. This module itself adds NO new updater.
* **uses cpu_local_snapshot**: NO (builder works on a gsd/HOOMD snapshot;
  the reused myosin updater uses ``get_snapshot``, same as cortex).
* **uses cKDTree / broad-phase**: NO at construction (α-actinin is placed by
  arithmetic along the known bundle axis). The reused myosin binder uses a
  KDTree as it already does in cortex — unchanged.
* **hot-path priority**: P2 (sparse basal compartment; far fewer particles
  than cortex; not in the per-step force loop).
* **GPU path now**: builtin (``md.bond.Harmonic`` is GPU-resident in HOOMD;
  the reused myosin updater follows the cortex GPU-main port plan).
* **native ForceCompute candidate**: NO — no custom per-step force is added;
  the only custom kernel involved is the shared myosin stepper.
* **bottleneck risk**: LOW. The SF compartment is small; the cost is in the
  shared myosin updater (already profiled for cortex), not here.

References
----------
- Sarcomeric α-actinin periodicity ~0.5-1 µm in non-muscle ventral stress
  fibers: Tojkander, Gateva & Lappalainen 2012, J Cell Sci 125:1855-1864
  ("Actin stress fibers — assembly, dynamics and biological roles");
  Hotulainen & Lappalainen 2006, J Cell Biol 173:383-394 (vSF arise from
  dorsal SF + transverse arcs; periodic α-actinin/myosin banding).
- Single ventral stress fiber contractile tension ~10-30 nN: Kumar, Maxwell,
  Heisterkamp, Polte, Lele, Salanga, Mazur & Ingber 2006, Biophys J
  90:3762-3773 (single-living-SF laser ablation, Kelvin-Voigt retraction).
- Traction stress ~5.5 nN/µm² at FA: Balaban et al. 2001, Nat Cell Biol
  3:466-472 (force on substrate at focal adhesions).
- NMII bipolar minifilament (D5) + Hill F-V (D6): Stam et al. 2017 PNAS;
  Hill 1938; Kovács 2003 — reused via :mod:`ffn_sim.cortex.myosin` /
  :mod:`ffn_sim.bridge.motor`.
- α-actinin slip-bond rates: Ferrer 2008 PNAS (k_off0 0.066 /s) — reused via
  :mod:`ffn_sim.cortex.crosslinkers` when the Lead wires SF crosslinker kinetics.
- Builder/resolve/Sanity-Gate pattern: :mod:`ffn_sim.cortex.erm`,
  :mod:`ffn_sim.cell.nucleus`, :mod:`ffn_sim.cortex.crosslinkers`.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

import numpy as np

import hoomd
import hoomd.md as md


# ===========================================================================
# Gamma denylist + open PI decisions
# ===========================================================================
#: Every bond type this module creates STARTS WITH this prefix, so the
#: cortical-tension estimator can denylist the non-cortical SF load path
#: (the SF tension is a BASAL observable, not cortical hoop γ).
GAMMA_DENYLIST_PREFIX: str = "sf_"

#: Open decisions surfaced to PI (CLAUDE.md "No empirical magic numbers": when a
#: constant is genuinely unknown, flag here + leave the field None + raise).
PI_DECISIONS: list[str] = [
    "k_actin (SF backbone bundle stiffness, N/m): no single-molecule "
    "literature value for a MESOSCALE ventral-SF actin-bundle segment at the "
    "×40 coarse scale. Default 1.0e-2 N/m is the ORDER implied by Kumar 2006 "
    "single-SF tension (~10-30 nN) over a ~µm sarcomeric strain, NOT a tuned "
    "fit; range-checked, flagged for PI ratification against a fine-grained "
    "bundle-of-N-filaments derivation.",
    "k_anchor (SF→FA anchor bond stiffness, N/m): set equal to k_actin "
    "(the anchor is as stiff as the bundle it terminates) pending a "
    "talin/vinculin clutch-stiffness anchor from the fa compartment — flagged.",
    "sf_myosin bond-type variant: NMII on SFs currently reuses the cortex "
    "'cortex_myosin_*' bond types (shared D5/D6 builder). A distinct 'sf_myosin_*' "
    "prefix is a TODO so SF motors are γ-denylisted SEPARATELY from cortical "
    "motors. Until then the Lead must denylist 'cortex_myosin_*' on SF builds.",
    "Bundle bending rigidity (angle potential): the bundle is built as a "
    "straight FA→FA chord with NO angle harmonic. SF persistence length / "
    "buckling under compression is a documented TODO (needs an EI anchor).",
]


# ===========================================================================
# Resolved parameters
# ===========================================================================
@dataclass(frozen=True, slots=True)
class ResolvedStressFibers:
    """Resolved ventral-stress-fiber parameters (SI units).

    All lengths in metres, stiffnesses in N/m, forces in N. A disabled
    compartment carries ``enabled=False`` and zeros so the builder no-ops.
    """

    enabled: bool

    n_SF: int                       # number of ventral stress-fiber bundles
    n_beads_per_SF: int             # explicit sf_actin beads along each bundle
    sarcomere_spacing: float        # m   α-actinin banding period (0.5-1 µm)

    # Stiffnesses (SI: N/m)
    k_actin: float | None           # N/m  sf_actin backbone bond stiffness (PI)
    k_anchor: float | None          # N/m  sf_anchor SF→FA bond stiffness (PI)
    k_xl: float                     # N/m  α-actinin intra/attach stiffness
    alpha_length: float             # m    α-actinin head-to-head rest length

    # Single-SF tension band (Kumar 2006) — VALIDATION band, not a force input.
    sf_tension_band_N: tuple[float, float]  # N   (10 nN, 30 nN)

    seed: int

    # Derived (filled by resolve_stress_fibers)
    n_xl_per_SF_hint: int = 0       # informational: sarcomeres per ~typical bundle
    extras: dict[str, Any] = field(default_factory=dict)


def _require_finite_positive(name: str, x: float) -> None:
    if not (math.isfinite(x) and x > 0.0):
        raise ValueError(f"{name} must be finite and > 0; got {x!r}")


def resolve_stress_fibers(
    cfg: dict,
    *,
    kT: float = 4.28e-21,
    R_cell: float | None = None,
    dt: float | None = None,
) -> ResolvedStressFibers:
    """Resolve the ``stress_fibers`` config block (DEFAULT-OFF).

    Args:
        cfg: The ``stress_fibers`` sub-dict, OR a parent dict that contains a
            ``stress_fibers`` key. When the block is missing, or contains
            ``enabled: false``, a disabled :class:`ResolvedStressFibers` is
            returned (all builders then no-op).
        kT: Thermal energy [J]; accepted for signature symmetry with the other
            resolvers (not used to set any SF constant — none are thermal).
        R_cell: Cell radius [m] — accepted for context; not required here.
        dt: Host timestep [s] — accepted for context (CFL gating is done by the
            attach helper, which has the per-bead drag in hand).

    Returns:
        A frozen :class:`ResolvedStressFibers`.

    Raises:
        ValueError: on negative / zero / non-finite parameters when ENABLED.
    """
    # Unwrap a parent config.
    if isinstance(cfg, dict) and "stress_fibers" in cfg:
        cfg = cfg["stress_fibers"]
    if cfg is None:
        cfg = {}

    enabled = bool(cfg.get("enabled", False))

    if not enabled:
        # OFF-identity: zeros, no PI-required field forced.
        return ResolvedStressFibers(
            enabled=False,
            n_SF=0,
            n_beads_per_SF=0,
            sarcomere_spacing=0.0,
            k_actin=None,
            k_anchor=None,
            k_xl=0.0,
            alpha_length=0.0,
            sf_tension_band_N=(0.0, 0.0),
            seed=int(cfg.get("seed", 47)),
        )

    n_SF = int(cfg.get("n_SF", 0))
    n_beads_per_SF = int(cfg.get("n_beads_per_SF", 24))
    # Sarcomeric α-actinin periodicity: 0.5-1 µm (Tojkander 2012 JCS;
    # Hotulainen-Lappalainen 2006 JCB). Default 0.5 µm (lower band — the
    # tighter banding seen in non-muscle ventral SFs).
    sarcomere_spacing = float(cfg.get("sarcomere_spacing", 0.5e-6))

    # k_actin / k_anchor: PI-flagged (no fine-grained mesoscale anchor yet).
    # Read from cfg if the PI has set them; otherwise carry the documented
    # default ORDER (Kumar 2006 ~10-30 nN over a ~µm strain → ~1e-2 N/m).
    k_actin = cfg.get("k_actin", 1.0e-2)
    k_actin = None if k_actin is None else float(k_actin)
    k_anchor = cfg.get("k_anchor", k_actin)
    k_anchor = None if k_anchor is None else float(k_anchor)

    # α-actinin crosslinker (reuse KU-3.19 vocabulary):
    #   k_xl   = 0.1 pN/µm = 1e-7 N/m  (Furuike 2001 / Ferrer 2008; same as
    #            cortex/crosslinkers.py k_intra default).
    #   alpha_length = 35 nm  (α-actinin head-to-head, KU-3.19).
    k_xl = float(cfg.get("k_xl", 1.0e-7))
    alpha_length = float(cfg.get("alpha_length", 35.0e-9))

    # Single-SF tension validation band (Kumar 2006 Biophys J 90:3762): ~10-30 nN.
    band = cfg.get("sf_tension_band_N", (10.0e-9, 30.0e-9))
    sf_tension_band_N = (float(band[0]), float(band[1]))

    seed = int(cfg.get("seed", 47))

    # ---- §2 boundary checks (ENABLED path) ----
    if n_SF < 0:
        raise ValueError(f"n_SF must be ≥ 0; got {n_SF}")
    if n_beads_per_SF < 2:
        raise ValueError(
            f"n_beads_per_SF must be ≥ 2 (a bundle spans FA→FA); "
            f"got {n_beads_per_SF}"
        )
    _require_finite_positive("sarcomere_spacing", sarcomere_spacing)
    _require_finite_positive("k_xl", k_xl)
    _require_finite_positive("alpha_length", alpha_length)
    if not (sf_tension_band_N[0] >= 0.0 and sf_tension_band_N[1] > sf_tension_band_N[0]):
        raise ValueError(
            f"sf_tension_band_N must be a positive ordered (lo, hi); "
            f"got {sf_tension_band_N}"
        )
    # k_actin / k_anchor may be None (PI-flagged disabled), else finite-positive.
    if k_actin is not None:
        _require_finite_positive("k_actin", k_actin)
    if k_anchor is not None:
        _require_finite_positive("k_anchor", k_anchor)

    # Informational hint: sarcomeres per a "typical" bundle of n_beads.
    # (Actual per-bundle count is geometry-dependent and computed at layout.)
    n_xl_hint = 0

    return ResolvedStressFibers(
        enabled=True,
        n_SF=n_SF,
        n_beads_per_SF=n_beads_per_SF,
        sarcomere_spacing=sarcomere_spacing,
        k_actin=k_actin,
        k_anchor=k_anchor,
        k_xl=k_xl,
        alpha_length=alpha_length,
        sf_tension_band_N=sf_tension_band_N,
        seed=seed,
        n_xl_per_SF_hint=n_xl_hint,
        extras={
            "kT": float(kT),
            "R_cell": (None if R_cell is None else float(R_cell)),
            "dt": (None if dt is None else float(dt)),
        },
    )


def stress_fiber_dt_cfl(
    p: ResolvedStressFibers, *, gamma_b: float, cfl_safety_factor: float = 0.1
) -> float:
    """Return the SF-stiffest-element CFL timestep ``cfl_safety · γ_b / k``.

    The stiffest SF element sets the step: ``k = max(k_actin, k_anchor)``.
    Mirrors the ERM CFL convention (D3 BAOAB).

    Raises:
        NotImplementedError: if ``k_actin`` is PI-flagged (None) — the CFL
            cannot be computed without the (PI-pending) backbone stiffness.
    """
    if p.k_actin is None:
        raise NotImplementedError(
            "stress_fiber_dt_cfl needs k_actin, which is PI-flagged None "
            "(see PI_DECISIONS). Set stress_fibers.k_actin to a ratified value."
        )
    k_anchor = p.k_anchor if p.k_anchor is not None else p.k_actin
    k_stiffest = max(p.k_actin, k_anchor)
    return cfl_safety_factor * gamma_b / k_stiffest


# ===========================================================================
# Bond type names
# ===========================================================================
BOND_TYPE_SF_ACTIN: str = "sf_actin_bond"        # load-bearing backbone chain
BOND_TYPE_SF_ANCHOR: str = "sf_anchor"           # SF end bead ↔ FA clutch particle
BOND_TYPE_SF_XLINK_INTRA: str = "sf_xlink_intra"  # α-actinin head ↔ head
BOND_TYPE_SF_XLINK_ATTACH: str = "sf_xlink_attach"  # α-actinin head ↔ sf_actin bead


def sf_bond_type_names() -> list[str]:
    """All HOOMD bond-type names this module creates (all ``sf_``-prefixed)."""
    return [
        BOND_TYPE_SF_ACTIN,
        BOND_TYPE_SF_ANCHOR,
        BOND_TYPE_SF_XLINK_INTRA,
        BOND_TYPE_SF_XLINK_ATTACH,
    ]


# ===========================================================================
# Layout
# ===========================================================================
@dataclass(slots=True)
class StressFiberLayout:
    """Per-bundle construction bookkeeping (tags + positions).

    Particle-block layout (appended after the existing ``n_part_old`` tags):
    for bundle ``b`` the block is ``[ sf_actin × n_beads_b ,
    sf_xlink_head × (2·n_sarc_b) ]``.

    Bond breakdown per bundle (all ``sf_``-prefixed):
      * ``n_beads_b − 1``   ``sf_actin_bond``     (backbone chain)
      * ``2``               ``sf_anchor``         (bead0↔FA_A, beadEnd↔FA_B)
      * ``n_sarc_b``        ``sf_xlink_intra``    (one per α-actinin period)
      * ``2·n_sarc_b``      ``sf_xlink_attach``   (each head → nearest bead)

    Attributes:
        actin_tags: list of (n_beads_b,) int arrays — global sf_actin bead tags.
        xlink_head_tags: list of (2·n_sarc_b,) int arrays — α-actinin head tags.
        actin_positions: list of (n_beads_b, 3) float64 bead positions.
        xlink_head_positions: list of (2·n_sarc_b, 3) float64 head positions.
        fa_endpoints: (n_SF, 2) int — the (FA_A_tag, FA_B_tag) per bundle.
        n_sarc: (n_SF,) int — α-actinin periods realised per bundle.
        ell0_actin: (n_SF,) float — backbone bead spacing per bundle.
        particle_tag_start: int — first appended particle tag.
    """

    actin_tags: list[np.ndarray]
    xlink_head_tags: list[np.ndarray]
    actin_positions: list[np.ndarray]
    xlink_head_positions: list[np.ndarray]
    fa_endpoints: np.ndarray
    n_sarc: np.ndarray
    ell0_actin: np.ndarray
    particle_tag_start: int


def generate_stress_fiber_layout(
    p: ResolvedStressFibers,
    fa_endpoint_positions: np.ndarray,
    fa_endpoint_tags: np.ndarray,
    *,
    particle_tag_start: int,
    rng: np.random.Generator | None = None,
) -> StressFiberLayout:
    """Lay out ``n_SF`` bundles between pairs of FA endpoint positions.

    Args:
        p: Resolved SF parameters (must be ``enabled``; a disabled ``p`` yields
            an empty layout).
        fa_endpoint_positions: (M, 3) float64 — positions of candidate FA clutch
            anchor particles (basal plane). ``M ≥ 2·n_SF`` is required so each
            bundle gets two DISTINCT endpoints.
        fa_endpoint_tags: (M,) int — global particle tags of those FA anchors
            (the ``sf_anchor`` bond ties an SF end bead to this tag).
        particle_tag_start: Global tag where the first appended SF particle sits
            (typically the current ``snap.particles.N``).
        rng: Optional RNG (default seeded from ``p.seed``).

    Returns:
        A :class:`StressFiberLayout`.

    Raises:
        ValueError: if too few FA endpoints, or a degenerate (zero-length)
            bundle would result.
    """
    if rng is None:
        rng = np.random.default_rng(p.seed)

    pos = np.asarray(fa_endpoint_positions, dtype=np.float64).reshape(-1, 3)
    tags = np.asarray(fa_endpoint_tags, dtype=np.int64).reshape(-1)
    if pos.shape[0] != tags.shape[0]:
        raise ValueError(
            "fa_endpoint_positions and fa_endpoint_tags length mismatch "
            f"({pos.shape[0]} vs {tags.shape[0]})."
        )

    if (not p.enabled) or p.n_SF == 0:
        return StressFiberLayout(
            actin_tags=[],
            xlink_head_tags=[],
            actin_positions=[],
            xlink_head_positions=[],
            fa_endpoints=np.empty((0, 2), dtype=np.int64),
            n_sarc=np.empty((0,), dtype=np.int64),
            ell0_actin=np.empty((0,), dtype=np.float64),
            particle_tag_start=particle_tag_start,
        )

    M = pos.shape[0]
    if M < 2 * p.n_SF:
        raise ValueError(
            f"need ≥ 2·n_SF = {2 * p.n_SF} FA endpoints to span {p.n_SF} "
            f"bundles with distinct ends; got {M}."
        )

    # Pair FA endpoints without reuse: shuffle, take consecutive pairs.
    order = rng.permutation(M)
    endpoint_pairs = order[: 2 * p.n_SF].reshape(p.n_SF, 2)

    actin_tags: list[np.ndarray] = []
    xlink_head_tags: list[np.ndarray] = []
    actin_positions: list[np.ndarray] = []
    xlink_head_positions: list[np.ndarray] = []
    fa_endpoints = np.empty((p.n_SF, 2), dtype=np.int64)
    n_sarc_arr = np.empty((p.n_SF,), dtype=np.int64)
    ell0_arr = np.empty((p.n_SF,), dtype=np.float64)

    next_tag = int(particle_tag_start)
    nb = p.n_beads_per_SF

    for b in range(p.n_SF):
        ia, ib = int(endpoint_pairs[b, 0]), int(endpoint_pairs[b, 1])
        A = pos[ia]
        B = pos[ib]
        fa_endpoints[b] = (int(tags[ia]), int(tags[ib]))

        axis = B - A
        L = float(np.linalg.norm(axis))
        if not (math.isfinite(L) and L > 0.0):
            raise ValueError(
                f"degenerate bundle {b}: FA endpoints coincide (|B−A| = {L})."
            )
        u = axis / L
        ell0 = L / (nb - 1)
        ell0_arr[b] = ell0

        # Backbone beads evenly along A→B.
        ts = np.linspace(0.0, 1.0, nb)
        beads = A[None, :] + ts[:, None] * axis[None, :]
        bead_tags = np.arange(next_tag, next_tag + nb, dtype=np.int64)
        next_tag += nb
        actin_positions.append(beads)
        actin_tags.append(bead_tags)

        # α-actinin sarcomeric banding: one crosslinker every sarcomere_spacing.
        # n_sarc = number of WHOLE periods that fit along the bundle length.
        n_sarc = int(max(1, round(L / p.sarcomere_spacing)))
        # Cap so heads always have a backbone bead nearby (≤ n_beads−1 periods).
        n_sarc = int(min(n_sarc, nb - 1))
        n_sarc_arr[b] = n_sarc

        # Band positions along the bundle (centres of each period).
        band_s = (np.arange(n_sarc) + 0.5) / n_sarc          # ∈ (0,1)
        band_pts = A[None, :] + band_s[:, None] * axis[None, :]
        # Lateral offset for the two α-actinin heads (perpendicular to axis),
        # half the rest length to each side so the intra bond is force-free.
        # Build any unit vector ⟂ u.
        ref = np.array([1.0, 0.0, 0.0]) if abs(u[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        perp = np.cross(u, ref)
        perp = perp / max(float(np.linalg.norm(perp)), 1e-30)
        half = 0.5 * p.alpha_length
        heads = np.empty((2 * n_sarc, 3), dtype=np.float64)
        heads[0::2] = band_pts - half * perp[None, :]
        heads[1::2] = band_pts + half * perp[None, :]
        head_tags = np.arange(next_tag, next_tag + 2 * n_sarc, dtype=np.int64)
        next_tag += 2 * n_sarc
        xlink_head_positions.append(heads)
        xlink_head_tags.append(head_tags)

    return StressFiberLayout(
        actin_tags=actin_tags,
        xlink_head_tags=xlink_head_tags,
        actin_positions=actin_positions,
        xlink_head_positions=xlink_head_positions,
        fa_endpoints=fa_endpoints,
        n_sarc=n_sarc_arr,
        ell0_actin=ell0_arr,
        particle_tag_start=particle_tag_start,
    )


# ===========================================================================
# Snapshot-extension builder
# ===========================================================================
def extend_snapshot_with_stress_fibers(
    base_snap,
    p: ResolvedStressFibers,
    fa_endpoint_positions: np.ndarray | None = None,
    fa_endpoint_tags: np.ndarray | None = None,
    *,
    rng: np.random.Generator | None = None,
):
    """Append explicit SF particles + bonds onto a gsd/HOOMD snapshot.

    DEFAULT-OFF: when ``p.enabled`` is False (or ``p.n_SF == 0``) this is a
    NO-OP and returns ``base_snap`` UNCHANGED (same object), adding zero
    particles and zero bonds. This is the OFF-identity contract.

    When enabled, it adds:
      * ``sf_actin`` + ``sf_xlink_head`` particle types,
      * the four ``sf_`` bond types (see :func:`sf_bond_type_names`),
      * per-bundle: backbone chain bonds, two FA-anchor bonds, α-actinin
        intra + attach bonds (sarcomeric banding).

    Args:
        base_snap: a ``gsd.hoomd.Frame``-like snapshot (the current cell state).
        p: resolved SF parameters.
        fa_endpoint_positions: (M, 3) FA anchor positions (REQUIRED when enabled
            and ``n_SF > 0``; this compartment REQUIRES the fa compartment).
        fa_endpoint_tags: (M,) FA anchor global particle tags.
        rng: optional RNG.

    Returns:
        The same ``base_snap`` (disabled) or a new extended ``gsd.hoomd.Frame``.

    Raises:
        ValueError: if enabled with ``n_SF > 0`` but FA endpoints are not given.
    """
    # --- OFF-identity early return ---
    if (not p.enabled) or p.n_SF == 0:
        return base_snap

    if fa_endpoint_positions is None or fa_endpoint_tags is None:
        raise ValueError(
            "ventral_stress_fibers requires the fa compartment: pass "
            "fa_endpoint_positions + fa_endpoint_tags (FA clutch anchors). "
            "This module does not invent substrate anchors."
        )

    import gsd.hoomd

    if rng is None:
        rng = np.random.default_rng(p.seed)

    snap_old = base_snap
    n_part_old = int(snap_old.particles.N)

    layout = generate_stress_fiber_layout(
        p,
        fa_endpoint_positions,
        fa_endpoint_tags,
        particle_tag_start=n_part_old,
        rng=rng,
    )

    # Totals.
    n_new_actin = sum(int(a.shape[0]) for a in layout.actin_tags)
    n_new_heads = sum(int(h.shape[0]) for h in layout.xlink_head_tags)
    n_new_particles = n_new_actin + n_new_heads

    snap = gsd.hoomd.Frame()
    snap.particles.N = n_part_old + n_new_particles

    # ---- particle types ----
    old_types = list(snap_old.particles.types) if snap_old.particles.types else []
    new_particle_types = list(old_types)
    for t in ("sf_actin", "sf_xlink_head"):
        if t not in new_particle_types:
            new_particle_types.append(t)
    sf_actin_tid = new_particle_types.index("sf_actin")
    sf_head_tid = new_particle_types.index("sf_xlink_head")
    snap.particles.types = new_particle_types

    # ---- typeids ----
    typeids = np.empty(snap.particles.N, dtype=np.uint32)
    if n_part_old > 0:
        typeids[:n_part_old] = np.asarray(snap_old.particles.typeid)
    # appended block: actin beads then heads, per bundle in layout order.
    cursor = n_part_old
    for b in range(p.n_SF):
        na = int(layout.actin_tags[b].shape[0])
        nh = int(layout.xlink_head_tags[b].shape[0])
        typeids[cursor:cursor + na] = sf_actin_tid
        cursor += na
        typeids[cursor:cursor + nh] = sf_head_tid
        cursor += nh
    snap.particles.typeid = typeids

    # ---- positions ----
    pos_new = np.empty((snap.particles.N, 3), dtype=np.float64)
    if n_part_old > 0:
        pos_new[:n_part_old] = np.asarray(snap_old.particles.position)
    cursor = n_part_old
    for b in range(p.n_SF):
        beads = layout.actin_positions[b]
        heads = layout.xlink_head_positions[b]
        na, nh = beads.shape[0], heads.shape[0]
        pos_new[cursor:cursor + na] = beads
        cursor += na
        pos_new[cursor:cursor + nh] = heads
        cursor += nh
    snap.particles.position = pos_new

    # ---- masses ----
    mass_new = np.empty(snap.particles.N, dtype=np.float64)
    if n_part_old > 0:
        mass_new[:n_part_old] = np.asarray(snap_old.particles.mass)
    mass_new[n_part_old:] = 1.0
    snap.particles.mass = mass_new

    # ---- bond types ----
    old_bond_types = list(snap_old.bonds.types) if snap_old.bonds.types else []
    new_bond_types = list(old_bond_types)
    for name in sf_bond_type_names():
        if name not in new_bond_types:
            new_bond_types.append(name)
    tid_chain = new_bond_types.index(BOND_TYPE_SF_ACTIN)
    tid_anchor = new_bond_types.index(BOND_TYPE_SF_ANCHOR)
    tid_intra = new_bond_types.index(BOND_TYPE_SF_XLINK_INTRA)
    tid_attach = new_bond_types.index(BOND_TYPE_SF_XLINK_ATTACH)

    # ---- old bonds ----
    if int(snap_old.bonds.N) > 0:
        old_bg = np.asarray(snap_old.bonds.group, dtype=np.uint32).reshape(-1, 2)
        old_bt = np.asarray(snap_old.bonds.typeid, dtype=np.uint32)
    else:
        old_bg = np.empty((0, 2), dtype=np.uint32)
        old_bt = np.empty((0,), dtype=np.uint32)

    # ---- new bonds ----
    new_groups: list[tuple[int, int]] = []
    new_btids: list[int] = []
    for b in range(p.n_SF):
        bead_tags = layout.actin_tags[b]
        head_tags = layout.xlink_head_tags[b]
        fa_a, fa_b = int(layout.fa_endpoints[b, 0]), int(layout.fa_endpoints[b, 1])
        nb = int(bead_tags.shape[0])

        # backbone chain
        for i in range(nb - 1):
            new_groups.append((int(bead_tags[i]), int(bead_tags[i + 1])))
            new_btids.append(tid_chain)
        # FA anchors: bead 0 ↔ FA_A, last bead ↔ FA_B
        new_groups.append((int(bead_tags[0]), fa_a))
        new_btids.append(tid_anchor)
        new_groups.append((int(bead_tags[nb - 1]), fa_b))
        new_btids.append(tid_anchor)
        # α-actinin: per period one intra (head pair) + two attach (head→bead)
        n_sarc = int(layout.n_sarc[b])
        for s in range(n_sarc):
            h0 = int(head_tags[2 * s])
            h1 = int(head_tags[2 * s + 1])
            new_groups.append((h0, h1))
            new_btids.append(tid_intra)
            # nearest backbone bead to this band centre (band centre is at
            # fractional position (s+0.5)/n_sarc → nearest bead index).
            frac = (s + 0.5) / n_sarc
            ib = int(min(nb - 1, max(0, round(frac * (nb - 1)))))
            new_groups.append((h0, int(bead_tags[ib])))
            new_btids.append(tid_attach)
            new_groups.append((h1, int(bead_tags[ib])))
            new_btids.append(tid_attach)

    if new_groups:
        new_bg = np.asarray(new_groups, dtype=np.uint32).reshape(-1, 2)
        new_bt = np.asarray(new_btids, dtype=np.uint32)
        snap.bonds.group = np.concatenate([old_bg, new_bg], axis=0)
        snap.bonds.typeid = np.concatenate([old_bt, new_bt], axis=0)
    else:
        snap.bonds.group = old_bg
        snap.bonds.typeid = old_bt
    snap.bonds.N = int(snap.bonds.group.shape[0])
    snap.bonds.types = new_bond_types

    # ---- pass through angles ----
    if int(snap_old.angles.N) > 0:
        snap.angles.N = int(snap_old.angles.N)
        snap.angles.types = list(snap_old.angles.types)
        snap.angles.typeid = np.asarray(snap_old.angles.typeid)
        snap.angles.group = np.asarray(snap_old.angles.group)

    snap.configuration.box = list(snap_old.configuration.box)

    # Stash the layout for the Lead (wiring myosin / measuring tension).
    return snap


# ===========================================================================
# Bond-param registration
# ===========================================================================
def register_stress_fiber_bond_params(
    bond: md.bond.Harmonic, p: ResolvedStressFibers, layout: StressFiberLayout
) -> None:
    """Wire ``md.bond.Harmonic`` params for the four ``sf_`` bond types.

    The backbone ``sf_actin_bond`` uses a SINGLE rest length: the mean bundle
    bead spacing (bundles built from FA→FA spans of similar length share a
    rest length; per-bundle ℓ0 variation is small for a basal layout). For a
    production build with widely varying bundle lengths the Lead should use a
    per-r0 binned family (TODO), mirroring the cortex attach binning.

    Raises:
        NotImplementedError: if ``k_actin`` / ``k_anchor`` are PI-flagged None.
    """
    if p.k_actin is None or p.k_anchor is None:
        raise NotImplementedError(
            "register_stress_fiber_bond_params needs k_actin and k_anchor, "
            "which are PI-flagged None (see PI_DECISIONS). Set ratified values "
            "in the stress_fibers config before building the SF force law."
        )
    ell0 = (
        float(np.mean(layout.ell0_actin))
        if layout.ell0_actin.size > 0
        else 0.0
    )
    bond.params[BOND_TYPE_SF_ACTIN] = dict(k=p.k_actin, r0=ell0)
    # Anchor rest length ≈ 0: the SF end bead is placed AT the FA endpoint so
    # the anchor is force-free at construction (physiological-baseline rule).
    bond.params[BOND_TYPE_SF_ANCHOR] = dict(k=p.k_anchor, r0=0.0)
    bond.params[BOND_TYPE_SF_XLINK_INTRA] = dict(k=p.k_xl, r0=p.alpha_length)
    # Attach r0 = 0: head placed at the band centre, bonded to the nearest
    # bead; small residual stretch is force-negligible at k_xl = 1e-7 N/m.
    bond.params[BOND_TYPE_SF_XLINK_ATTACH] = dict(k=p.k_xl, r0=0.0)


# ===========================================================================
# Basal observable: SF axial tension (DENYLISTED from γ)
# ===========================================================================
def measure_sf_tension(
    positions_by_tag: np.ndarray,
    bond_group: np.ndarray,
    bond_typeid: np.ndarray,
    bond_types: list[str],
    p: ResolvedStressFibers,
    *,
    r0: float | None = None,
) -> dict[str, float]:
    """Mean axial tension of the ``sf_actin_bond`` backbone (basal observable).

    This is the SF analogue of the single-SF force band (Kumar 2006 ~10-30 nN).
    It is summed ONLY over the ``sf_actin_bond`` load path and is NEVER part of
    the cortical-tension γ (the bond type is ``sf_``-prefixed → denylisted).

    Args:
        positions_by_tag: (N, 3) positions indexed by particle tag.
        bond_group: (B, 2) bond endpoint tags.
        bond_typeid: (B,) per-bond type id.
        bond_types: bond-type name list (type-id order).
        p: resolved SF parameters (provides ``k_actin``).
        r0: construction rest length [m] — the bond's registered ``r0``
            (``mean(layout.ell0_actin)``). REQUIRED for a trustworthy tension on a
            uniformly contracted bundle; if ``None`` it falls back to the live mean
            bond length and sets ``r0_is_live=1.0`` in the result.

    Returns:
        dict with ``mean_tension_N``, ``max_tension_N``, ``n_bonds``, ``in_band``
        (whether mean is inside ``p.sf_tension_band_N``), and ``r0_is_live``.

    Raises:
        NotImplementedError: if ``k_actin`` is PI-flagged None.
    """
    if p.k_actin is None:
        raise NotImplementedError(
            "measure_sf_tension needs k_actin (PI-flagged None); set a ratified "
            "value before measuring SF tension."
        )
    pos = np.asarray(positions_by_tag, dtype=np.float64)
    bg = np.asarray(bond_group, dtype=np.int64).reshape(-1, 2)
    bt = np.asarray(bond_typeid)
    try:
        chain_tid = bond_types.index(BOND_TYPE_SF_ACTIN)
    except ValueError:
        return dict(mean_tension_N=0.0, max_tension_N=0.0, n_bonds=0.0, in_band=0.0)
    mask = bt == chain_tid
    sel = bg[mask]
    if sel.shape[0] == 0:
        return dict(mean_tension_N=0.0, max_tension_N=0.0, n_bonds=0.0, in_band=0.0)
    dr = pos[sel[:, 0]] - pos[sel[:, 1]]
    r = np.linalg.norm(dr, axis=1)
    # Reference rest length r0 MUST be the CONSTRUCTION rest length (the bond's
    # registered r0 = mean ell0_actin, see register_stress_fiber_bond_params),
    # NOT the live mean bond length. Using the live mean would make a uniformly
    # contracted bundle (r approx constant) report ~0 tension — exactly the
    # physiological load case we want to measure. Caller passes the registered
    # r0; if omitted we fall back to the live mean but flag it via r0_is_live.
    r0_is_live = r0 is None
    if r0 is None:
        r0 = float(np.mean(r))
    tension = p.k_actin * np.clip(r - float(r0), 0.0, None)
    mean_T = float(np.mean(tension))
    lo, hi = p.sf_tension_band_N
    return dict(
        mean_tension_N=mean_T,
        max_tension_N=float(np.max(tension)),
        n_bonds=float(sel.shape[0]),
        in_band=float(lo <= mean_T <= hi),
        # 1.0 when r0 fell back to the live mean (under-reports uniform tension —
        # pass the registered construction r0 for the trustworthy number).
        r0_is_live=float(r0_is_live),
    )
